// Code generated by ent, DO NOT EDIT.

package artist

import (
	"spotter/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Artist {
	return predicate.Artist(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Artist {
	return predicate.Artist(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Artist {
	return predicate.Artist(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Artist {
	return predicate.Artist(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Artist {
	return predicate.Artist(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Artist {
	return predicate.Artist(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Artist {
	return predicate.Artist(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Artist {
	return predicate.Artist(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Artist {
	return predicate.Artist(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Artist {
	return predicate.Artist(sql.FieldEQ(FieldName, v))
}

// SortName applies equality check predicate on the "sort_name" field. It's identical to SortNameEQ.
func SortName(v string) predicate.Artist {
	return predicate.Artist(sql.FieldEQ(FieldSortName, v))
}

// MusicbrainzID applies equality check predicate on the "musicbrainz_id" field. It's identical to MusicbrainzIDEQ.
func MusicbrainzID(v string) predicate.Artist {
	return predicate.Artist(sql.FieldEQ(FieldMusicbrainzID, v))
}

// SpotifyID applies equality check predicate on the "spotify_id" field. It's identical to SpotifyIDEQ.
func SpotifyID(v string) predicate.Artist {
	return predicate.Artist(sql.FieldEQ(FieldSpotifyID, v))
}

// LastfmURL applies equality check predicate on the "lastfm_url" field. It's identical to LastfmURLEQ.
func LastfmURL(v string) predicate.Artist {
	return predicate.Artist(sql.FieldEQ(FieldLastfmURL, v))
}

// NavidromeID applies equality check predicate on the "navidrome_id" field. It's identical to NavidromeIDEQ.
func NavidromeID(v string) predicate.Artist {
	return predicate.Artist(sql.FieldEQ(FieldNavidromeID, v))
}

// Bio applies equality check predicate on the "bio" field. It's identical to BioEQ.
func Bio(v string) predicate.Artist {
	return predicate.Artist(sql.FieldEQ(FieldBio, v))
}

// Popularity applies equality check predicate on the "popularity" field. It's identical to PopularityEQ.
func Popularity(v int) predicate.Artist {
	return predicate.Artist(sql.FieldEQ(FieldPopularity, v))
}

// FollowerCount applies equality check predicate on the "follower_count" field. It's identical to FollowerCountEQ.
func FollowerCount(v int) predicate.Artist {
	return predicate.Artist(sql.FieldEQ(FieldFollowerCount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Artist {
	return predicate.Artist(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Artist {
	return predicate.Artist(sql.FieldEQ(FieldUpdatedAt, v))
}

// LastEnrichedAt applies equality check predicate on the "last_enriched_at" field. It's identical to LastEnrichedAtEQ.
func LastEnrichedAt(v time.Time) predicate.Artist {
	return predicate.Artist(sql.FieldEQ(FieldLastEnrichedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Artist {
	return predicate.Artist(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Artist {
	return predicate.Artist(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Artist {
	return predicate.Artist(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Artist {
	return predicate.Artist(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Artist {
	return predicate.Artist(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Artist {
	return predicate.Artist(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Artist {
	return predicate.Artist(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Artist {
	return predicate.Artist(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Artist {
	return predicate.Artist(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Artist {
	return predicate.Artist(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Artist {
	return predicate.Artist(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Artist {
	return predicate.Artist(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Artist {
	return predicate.Artist(sql.FieldContainsFold(FieldName, v))
}

// SortNameEQ applies the EQ predicate on the "sort_name" field.
func SortNameEQ(v string) predicate.Artist {
	return predicate.Artist(sql.FieldEQ(FieldSortName, v))
}

// SortNameNEQ applies the NEQ predicate on the "sort_name" field.
func SortNameNEQ(v string) predicate.Artist {
	return predicate.Artist(sql.FieldNEQ(FieldSortName, v))
}

// SortNameIn applies the In predicate on the "sort_name" field.
func SortNameIn(vs ...string) predicate.Artist {
	return predicate.Artist(sql.FieldIn(FieldSortName, vs...))
}

// SortNameNotIn applies the NotIn predicate on the "sort_name" field.
func SortNameNotIn(vs ...string) predicate.Artist {
	return predicate.Artist(sql.FieldNotIn(FieldSortName, vs...))
}

// SortNameGT applies the GT predicate on the "sort_name" field.
func SortNameGT(v string) predicate.Artist {
	return predicate.Artist(sql.FieldGT(FieldSortName, v))
}

// SortNameGTE applies the GTE predicate on the "sort_name" field.
func SortNameGTE(v string) predicate.Artist {
	return predicate.Artist(sql.FieldGTE(FieldSortName, v))
}

// SortNameLT applies the LT predicate on the "sort_name" field.
func SortNameLT(v string) predicate.Artist {
	return predicate.Artist(sql.FieldLT(FieldSortName, v))
}

// SortNameLTE applies the LTE predicate on the "sort_name" field.
func SortNameLTE(v string) predicate.Artist {
	return predicate.Artist(sql.FieldLTE(FieldSortName, v))
}

// SortNameContains applies the Contains predicate on the "sort_name" field.
func SortNameContains(v string) predicate.Artist {
	return predicate.Artist(sql.FieldContains(FieldSortName, v))
}

// SortNameHasPrefix applies the HasPrefix predicate on the "sort_name" field.
func SortNameHasPrefix(v string) predicate.Artist {
	return predicate.Artist(sql.FieldHasPrefix(FieldSortName, v))
}

// SortNameHasSuffix applies the HasSuffix predicate on the "sort_name" field.
func SortNameHasSuffix(v string) predicate.Artist {
	return predicate.Artist(sql.FieldHasSuffix(FieldSortName, v))
}

// SortNameIsNil applies the IsNil predicate on the "sort_name" field.
func SortNameIsNil() predicate.Artist {
	return predicate.Artist(sql.FieldIsNull(FieldSortName))
}

// SortNameNotNil applies the NotNil predicate on the "sort_name" field.
func SortNameNotNil() predicate.Artist {
	return predicate.Artist(sql.FieldNotNull(FieldSortName))
}

// SortNameEqualFold applies the EqualFold predicate on the "sort_name" field.
func SortNameEqualFold(v string) predicate.Artist {
	return predicate.Artist(sql.FieldEqualFold(FieldSortName, v))
}

// SortNameContainsFold applies the ContainsFold predicate on the "sort_name" field.
func SortNameContainsFold(v string) predicate.Artist {
	return predicate.Artist(sql.FieldContainsFold(FieldSortName, v))
}

// MusicbrainzIDEQ applies the EQ predicate on the "musicbrainz_id" field.
func MusicbrainzIDEQ(v string) predicate.Artist {
	return predicate.Artist(sql.FieldEQ(FieldMusicbrainzID, v))
}

// MusicbrainzIDNEQ applies the NEQ predicate on the "musicbrainz_id" field.
func MusicbrainzIDNEQ(v string) predicate.Artist {
	return predicate.Artist(sql.FieldNEQ(FieldMusicbrainzID, v))
}

// MusicbrainzIDIn applies the In predicate on the "musicbrainz_id" field.
func MusicbrainzIDIn(vs ...string) predicate.Artist {
	return predicate.Artist(sql.FieldIn(FieldMusicbrainzID, vs...))
}

// MusicbrainzIDNotIn applies the NotIn predicate on the "musicbrainz_id" field.
func MusicbrainzIDNotIn(vs ...string) predicate.Artist {
	return predicate.Artist(sql.FieldNotIn(FieldMusicbrainzID, vs...))
}

// MusicbrainzIDGT applies the GT predicate on the "musicbrainz_id" field.
func MusicbrainzIDGT(v string) predicate.Artist {
	return predicate.Artist(sql.FieldGT(FieldMusicbrainzID, v))
}

// MusicbrainzIDGTE applies the GTE predicate on the "musicbrainz_id" field.
func MusicbrainzIDGTE(v string) predicate.Artist {
	return predicate.Artist(sql.FieldGTE(FieldMusicbrainzID, v))
}

// MusicbrainzIDLT applies the LT predicate on the "musicbrainz_id" field.
func MusicbrainzIDLT(v string) predicate.Artist {
	return predicate.Artist(sql.FieldLT(FieldMusicbrainzID, v))
}

// MusicbrainzIDLTE applies the LTE predicate on the "musicbrainz_id" field.
func MusicbrainzIDLTE(v string) predicate.Artist {
	return predicate.Artist(sql.FieldLTE(FieldMusicbrainzID, v))
}

// MusicbrainzIDContains applies the Contains predicate on the "musicbrainz_id" field.
func MusicbrainzIDContains(v string) predicate.Artist {
	return predicate.Artist(sql.FieldContains(FieldMusicbrainzID, v))
}

// MusicbrainzIDHasPrefix applies the HasPrefix predicate on the "musicbrainz_id" field.
func MusicbrainzIDHasPrefix(v string) predicate.Artist {
	return predicate.Artist(sql.FieldHasPrefix(FieldMusicbrainzID, v))
}

// MusicbrainzIDHasSuffix applies the HasSuffix predicate on the "musicbrainz_id" field.
func MusicbrainzIDHasSuffix(v string) predicate.Artist {
	return predicate.Artist(sql.FieldHasSuffix(FieldMusicbrainzID, v))
}

// MusicbrainzIDIsNil applies the IsNil predicate on the "musicbrainz_id" field.
func MusicbrainzIDIsNil() predicate.Artist {
	return predicate.Artist(sql.FieldIsNull(FieldMusicbrainzID))
}

// MusicbrainzIDNotNil applies the NotNil predicate on the "musicbrainz_id" field.
func MusicbrainzIDNotNil() predicate.Artist {
	return predicate.Artist(sql.FieldNotNull(FieldMusicbrainzID))
}

// MusicbrainzIDEqualFold applies the EqualFold predicate on the "musicbrainz_id" field.
func MusicbrainzIDEqualFold(v string) predicate.Artist {
	return predicate.Artist(sql.FieldEqualFold(FieldMusicbrainzID, v))
}

// MusicbrainzIDContainsFold applies the ContainsFold predicate on the "musicbrainz_id" field.
func MusicbrainzIDContainsFold(v string) predicate.Artist {
	return predicate.Artist(sql.FieldContainsFold(FieldMusicbrainzID, v))
}

// SpotifyIDEQ applies the EQ predicate on the "spotify_id" field.
func SpotifyIDEQ(v string) predicate.Artist {
	return predicate.Artist(sql.FieldEQ(FieldSpotifyID, v))
}

// SpotifyIDNEQ applies the NEQ predicate on the "spotify_id" field.
func SpotifyIDNEQ(v string) predicate.Artist {
	return predicate.Artist(sql.FieldNEQ(FieldSpotifyID, v))
}

// SpotifyIDIn applies the In predicate on the "spotify_id" field.
func SpotifyIDIn(vs ...string) predicate.Artist {
	return predicate.Artist(sql.FieldIn(FieldSpotifyID, vs...))
}

// SpotifyIDNotIn applies the NotIn predicate on the "spotify_id" field.
func SpotifyIDNotIn(vs ...string) predicate.Artist {
	return predicate.Artist(sql.FieldNotIn(FieldSpotifyID, vs...))
}

// SpotifyIDGT applies the GT predicate on the "spotify_id" field.
func SpotifyIDGT(v string) predicate.Artist {
	return predicate.Artist(sql.FieldGT(FieldSpotifyID, v))
}

// SpotifyIDGTE applies the GTE predicate on the "spotify_id" field.
func SpotifyIDGTE(v string) predicate.Artist {
	return predicate.Artist(sql.FieldGTE(FieldSpotifyID, v))
}

// SpotifyIDLT applies the LT predicate on the "spotify_id" field.
func SpotifyIDLT(v string) predicate.Artist {
	return predicate.Artist(sql.FieldLT(FieldSpotifyID, v))
}

// SpotifyIDLTE applies the LTE predicate on the "spotify_id" field.
func SpotifyIDLTE(v string) predicate.Artist {
	return predicate.Artist(sql.FieldLTE(FieldSpotifyID, v))
}

// SpotifyIDContains applies the Contains predicate on the "spotify_id" field.
func SpotifyIDContains(v string) predicate.Artist {
	return predicate.Artist(sql.FieldContains(FieldSpotifyID, v))
}

// SpotifyIDHasPrefix applies the HasPrefix predicate on the "spotify_id" field.
func SpotifyIDHasPrefix(v string) predicate.Artist {
	return predicate.Artist(sql.FieldHasPrefix(FieldSpotifyID, v))
}

// SpotifyIDHasSuffix applies the HasSuffix predicate on the "spotify_id" field.
func SpotifyIDHasSuffix(v string) predicate.Artist {
	return predicate.Artist(sql.FieldHasSuffix(FieldSpotifyID, v))
}

// SpotifyIDIsNil applies the IsNil predicate on the "spotify_id" field.
func SpotifyIDIsNil() predicate.Artist {
	return predicate.Artist(sql.FieldIsNull(FieldSpotifyID))
}

// SpotifyIDNotNil applies the NotNil predicate on the "spotify_id" field.
func SpotifyIDNotNil() predicate.Artist {
	return predicate.Artist(sql.FieldNotNull(FieldSpotifyID))
}

// SpotifyIDEqualFold applies the EqualFold predicate on the "spotify_id" field.
func SpotifyIDEqualFold(v string) predicate.Artist {
	return predicate.Artist(sql.FieldEqualFold(FieldSpotifyID, v))
}

// SpotifyIDContainsFold applies the ContainsFold predicate on the "spotify_id" field.
func SpotifyIDContainsFold(v string) predicate.Artist {
	return predicate.Artist(sql.FieldContainsFold(FieldSpotifyID, v))
}

// LastfmURLEQ applies the EQ predicate on the "lastfm_url" field.
func LastfmURLEQ(v string) predicate.Artist {
	return predicate.Artist(sql.FieldEQ(FieldLastfmURL, v))
}

// LastfmURLNEQ applies the NEQ predicate on the "lastfm_url" field.
func LastfmURLNEQ(v string) predicate.Artist {
	return predicate.Artist(sql.FieldNEQ(FieldLastfmURL, v))
}

// LastfmURLIn applies the In predicate on the "lastfm_url" field.
func LastfmURLIn(vs ...string) predicate.Artist {
	return predicate.Artist(sql.FieldIn(FieldLastfmURL, vs...))
}

// LastfmURLNotIn applies the NotIn predicate on the "lastfm_url" field.
func LastfmURLNotIn(vs ...string) predicate.Artist {
	return predicate.Artist(sql.FieldNotIn(FieldLastfmURL, vs...))
}

// LastfmURLGT applies the GT predicate on the "lastfm_url" field.
func LastfmURLGT(v string) predicate.Artist {
	return predicate.Artist(sql.FieldGT(FieldLastfmURL, v))
}

// LastfmURLGTE applies the GTE predicate on the "lastfm_url" field.
func LastfmURLGTE(v string) predicate.Artist {
	return predicate.Artist(sql.FieldGTE(FieldLastfmURL, v))
}

// LastfmURLLT applies the LT predicate on the "lastfm_url" field.
func LastfmURLLT(v string) predicate.Artist {
	return predicate.Artist(sql.FieldLT(FieldLastfmURL, v))
}

// LastfmURLLTE applies the LTE predicate on the "lastfm_url" field.
func LastfmURLLTE(v string) predicate.Artist {
	return predicate.Artist(sql.FieldLTE(FieldLastfmURL, v))
}

// LastfmURLContains applies the Contains predicate on the "lastfm_url" field.
func LastfmURLContains(v string) predicate.Artist {
	return predicate.Artist(sql.FieldContains(FieldLastfmURL, v))
}

// LastfmURLHasPrefix applies the HasPrefix predicate on the "lastfm_url" field.
func LastfmURLHasPrefix(v string) predicate.Artist {
	return predicate.Artist(sql.FieldHasPrefix(FieldLastfmURL, v))
}

// LastfmURLHasSuffix applies the HasSuffix predicate on the "lastfm_url" field.
func LastfmURLHasSuffix(v string) predicate.Artist {
	return predicate.Artist(sql.FieldHasSuffix(FieldLastfmURL, v))
}

// LastfmURLIsNil applies the IsNil predicate on the "lastfm_url" field.
func LastfmURLIsNil() predicate.Artist {
	return predicate.Artist(sql.FieldIsNull(FieldLastfmURL))
}

// LastfmURLNotNil applies the NotNil predicate on the "lastfm_url" field.
func LastfmURLNotNil() predicate.Artist {
	return predicate.Artist(sql.FieldNotNull(FieldLastfmURL))
}

// LastfmURLEqualFold applies the EqualFold predicate on the "lastfm_url" field.
func LastfmURLEqualFold(v string) predicate.Artist {
	return predicate.Artist(sql.FieldEqualFold(FieldLastfmURL, v))
}

// LastfmURLContainsFold applies the ContainsFold predicate on the "lastfm_url" field.
func LastfmURLContainsFold(v string) predicate.Artist {
	return predicate.Artist(sql.FieldContainsFold(FieldLastfmURL, v))
}

// NavidromeIDEQ applies the EQ predicate on the "navidrome_id" field.
func NavidromeIDEQ(v string) predicate.Artist {
	return predicate.Artist(sql.FieldEQ(FieldNavidromeID, v))
}

// NavidromeIDNEQ applies the NEQ predicate on the "navidrome_id" field.
func NavidromeIDNEQ(v string) predicate.Artist {
	return predicate.Artist(sql.FieldNEQ(FieldNavidromeID, v))
}

// NavidromeIDIn applies the In predicate on the "navidrome_id" field.
func NavidromeIDIn(vs ...string) predicate.Artist {
	return predicate.Artist(sql.FieldIn(FieldNavidromeID, vs...))
}

// NavidromeIDNotIn applies the NotIn predicate on the "navidrome_id" field.
func NavidromeIDNotIn(vs ...string) predicate.Artist {
	return predicate.Artist(sql.FieldNotIn(FieldNavidromeID, vs...))
}

// NavidromeIDGT applies the GT predicate on the "navidrome_id" field.
func NavidromeIDGT(v string) predicate.Artist {
	return predicate.Artist(sql.FieldGT(FieldNavidromeID, v))
}

// NavidromeIDGTE applies the GTE predicate on the "navidrome_id" field.
func NavidromeIDGTE(v string) predicate.Artist {
	return predicate.Artist(sql.FieldGTE(FieldNavidromeID, v))
}

// NavidromeIDLT applies the LT predicate on the "navidrome_id" field.
func NavidromeIDLT(v string) predicate.Artist {
	return predicate.Artist(sql.FieldLT(FieldNavidromeID, v))
}

// NavidromeIDLTE applies the LTE predicate on the "navidrome_id" field.
func NavidromeIDLTE(v string) predicate.Artist {
	return predicate.Artist(sql.FieldLTE(FieldNavidromeID, v))
}

// NavidromeIDContains applies the Contains predicate on the "navidrome_id" field.
func NavidromeIDContains(v string) predicate.Artist {
	return predicate.Artist(sql.FieldContains(FieldNavidromeID, v))
}

// NavidromeIDHasPrefix applies the HasPrefix predicate on the "navidrome_id" field.
func NavidromeIDHasPrefix(v string) predicate.Artist {
	return predicate.Artist(sql.FieldHasPrefix(FieldNavidromeID, v))
}

// NavidromeIDHasSuffix applies the HasSuffix predicate on the "navidrome_id" field.
func NavidromeIDHasSuffix(v string) predicate.Artist {
	return predicate.Artist(sql.FieldHasSuffix(FieldNavidromeID, v))
}

// NavidromeIDIsNil applies the IsNil predicate on the "navidrome_id" field.
func NavidromeIDIsNil() predicate.Artist {
	return predicate.Artist(sql.FieldIsNull(FieldNavidromeID))
}

// NavidromeIDNotNil applies the NotNil predicate on the "navidrome_id" field.
func NavidromeIDNotNil() predicate.Artist {
	return predicate.Artist(sql.FieldNotNull(FieldNavidromeID))
}

// NavidromeIDEqualFold applies the EqualFold predicate on the "navidrome_id" field.
func NavidromeIDEqualFold(v string) predicate.Artist {
	return predicate.Artist(sql.FieldEqualFold(FieldNavidromeID, v))
}

// NavidromeIDContainsFold applies the ContainsFold predicate on the "navidrome_id" field.
func NavidromeIDContainsFold(v string) predicate.Artist {
	return predicate.Artist(sql.FieldContainsFold(FieldNavidromeID, v))
}

// BioEQ applies the EQ predicate on the "bio" field.
func BioEQ(v string) predicate.Artist {
	return predicate.Artist(sql.FieldEQ(FieldBio, v))
}

// BioNEQ applies the NEQ predicate on the "bio" field.
func BioNEQ(v string) predicate.Artist {
	return predicate.Artist(sql.FieldNEQ(FieldBio, v))
}

// BioIn applies the In predicate on the "bio" field.
func BioIn(vs ...string) predicate.Artist {
	return predicate.Artist(sql.FieldIn(FieldBio, vs...))
}

// BioNotIn applies the NotIn predicate on the "bio" field.
func BioNotIn(vs ...string) predicate.Artist {
	return predicate.Artist(sql.FieldNotIn(FieldBio, vs...))
}

// BioGT applies the GT predicate on the "bio" field.
func BioGT(v string) predicate.Artist {
	return predicate.Artist(sql.FieldGT(FieldBio, v))
}

// BioGTE applies the GTE predicate on the "bio" field.
func BioGTE(v string) predicate.Artist {
	return predicate.Artist(sql.FieldGTE(FieldBio, v))
}

// BioLT applies the LT predicate on the "bio" field.
func BioLT(v string) predicate.Artist {
	return predicate.Artist(sql.FieldLT(FieldBio, v))
}

// BioLTE applies the LTE predicate on the "bio" field.
func BioLTE(v string) predicate.Artist {
	return predicate.Artist(sql.FieldLTE(FieldBio, v))
}

// BioContains applies the Contains predicate on the "bio" field.
func BioContains(v string) predicate.Artist {
	return predicate.Artist(sql.FieldContains(FieldBio, v))
}

// BioHasPrefix applies the HasPrefix predicate on the "bio" field.
func BioHasPrefix(v string) predicate.Artist {
	return predicate.Artist(sql.FieldHasPrefix(FieldBio, v))
}

// BioHasSuffix applies the HasSuffix predicate on the "bio" field.
func BioHasSuffix(v string) predicate.Artist {
	return predicate.Artist(sql.FieldHasSuffix(FieldBio, v))
}

// BioIsNil applies the IsNil predicate on the "bio" field.
func BioIsNil() predicate.Artist {
	return predicate.Artist(sql.FieldIsNull(FieldBio))
}

// BioNotNil applies the NotNil predicate on the "bio" field.
func BioNotNil() predicate.Artist {
	return predicate.Artist(sql.FieldNotNull(FieldBio))
}

// BioEqualFold applies the EqualFold predicate on the "bio" field.
func BioEqualFold(v string) predicate.Artist {
	return predicate.Artist(sql.FieldEqualFold(FieldBio, v))
}

// BioContainsFold applies the ContainsFold predicate on the "bio" field.
func BioContainsFold(v string) predicate.Artist {
	return predicate.Artist(sql.FieldContainsFold(FieldBio, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.Artist {
	return predicate.Artist(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.Artist {
	return predicate.Artist(sql.FieldNotNull(FieldTags))
}

// PopularityEQ applies the EQ predicate on the "popularity" field.
func PopularityEQ(v int) predicate.Artist {
	return predicate.Artist(sql.FieldEQ(FieldPopularity, v))
}

// PopularityNEQ applies the NEQ predicate on the "popularity" field.
func PopularityNEQ(v int) predicate.Artist {
	return predicate.Artist(sql.FieldNEQ(FieldPopularity, v))
}

// PopularityIn applies the In predicate on the "popularity" field.
func PopularityIn(vs ...int) predicate.Artist {
	return predicate.Artist(sql.FieldIn(FieldPopularity, vs...))
}

// PopularityNotIn applies the NotIn predicate on the "popularity" field.
func PopularityNotIn(vs ...int) predicate.Artist {
	return predicate.Artist(sql.FieldNotIn(FieldPopularity, vs...))
}

// PopularityGT applies the GT predicate on the "popularity" field.
func PopularityGT(v int) predicate.Artist {
	return predicate.Artist(sql.FieldGT(FieldPopularity, v))
}

// PopularityGTE applies the GTE predicate on the "popularity" field.
func PopularityGTE(v int) predicate.Artist {
	return predicate.Artist(sql.FieldGTE(FieldPopularity, v))
}

// PopularityLT applies the LT predicate on the "popularity" field.
func PopularityLT(v int) predicate.Artist {
	return predicate.Artist(sql.FieldLT(FieldPopularity, v))
}

// PopularityLTE applies the LTE predicate on the "popularity" field.
func PopularityLTE(v int) predicate.Artist {
	return predicate.Artist(sql.FieldLTE(FieldPopularity, v))
}

// PopularityIsNil applies the IsNil predicate on the "popularity" field.
func PopularityIsNil() predicate.Artist {
	return predicate.Artist(sql.FieldIsNull(FieldPopularity))
}

// PopularityNotNil applies the NotNil predicate on the "popularity" field.
func PopularityNotNil() predicate.Artist {
	return predicate.Artist(sql.FieldNotNull(FieldPopularity))
}

// FollowerCountEQ applies the EQ predicate on the "follower_count" field.
func FollowerCountEQ(v int) predicate.Artist {
	return predicate.Artist(sql.FieldEQ(FieldFollowerCount, v))
}

// FollowerCountNEQ applies the NEQ predicate on the "follower_count" field.
func FollowerCountNEQ(v int) predicate.Artist {
	return predicate.Artist(sql.FieldNEQ(FieldFollowerCount, v))
}

// FollowerCountIn applies the In predicate on the "follower_count" field.
func FollowerCountIn(vs ...int) predicate.Artist {
	return predicate.Artist(sql.FieldIn(FieldFollowerCount, vs...))
}

// FollowerCountNotIn applies the NotIn predicate on the "follower_count" field.
func FollowerCountNotIn(vs ...int) predicate.Artist {
	return predicate.Artist(sql.FieldNotIn(FieldFollowerCount, vs...))
}

// FollowerCountGT applies the GT predicate on the "follower_count" field.
func FollowerCountGT(v int) predicate.Artist {
	return predicate.Artist(sql.FieldGT(FieldFollowerCount, v))
}

// FollowerCountGTE applies the GTE predicate on the "follower_count" field.
func FollowerCountGTE(v int) predicate.Artist {
	return predicate.Artist(sql.FieldGTE(FieldFollowerCount, v))
}

// FollowerCountLT applies the LT predicate on the "follower_count" field.
func FollowerCountLT(v int) predicate.Artist {
	return predicate.Artist(sql.FieldLT(FieldFollowerCount, v))
}

// FollowerCountLTE applies the LTE predicate on the "follower_count" field.
func FollowerCountLTE(v int) predicate.Artist {
	return predicate.Artist(sql.FieldLTE(FieldFollowerCount, v))
}

// FollowerCountIsNil applies the IsNil predicate on the "follower_count" field.
func FollowerCountIsNil() predicate.Artist {
	return predicate.Artist(sql.FieldIsNull(FieldFollowerCount))
}

// FollowerCountNotNil applies the NotNil predicate on the "follower_count" field.
func FollowerCountNotNil() predicate.Artist {
	return predicate.Artist(sql.FieldNotNull(FieldFollowerCount))
}

// GenresIsNil applies the IsNil predicate on the "genres" field.
func GenresIsNil() predicate.Artist {
	return predicate.Artist(sql.FieldIsNull(FieldGenres))
}

// GenresNotNil applies the NotNil predicate on the "genres" field.
func GenresNotNil() predicate.Artist {
	return predicate.Artist(sql.FieldNotNull(FieldGenres))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Artist {
	return predicate.Artist(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Artist {
	return predicate.Artist(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Artist {
	return predicate.Artist(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Artist {
	return predicate.Artist(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Artist {
	return predicate.Artist(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Artist {
	return predicate.Artist(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Artist {
	return predicate.Artist(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Artist {
	return predicate.Artist(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Artist {
	return predicate.Artist(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Artist {
	return predicate.Artist(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Artist {
	return predicate.Artist(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Artist {
	return predicate.Artist(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Artist {
	return predicate.Artist(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Artist {
	return predicate.Artist(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Artist {
	return predicate.Artist(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Artist {
	return predicate.Artist(sql.FieldLTE(FieldUpdatedAt, v))
}

// LastEnrichedAtEQ applies the EQ predicate on the "last_enriched_at" field.
func LastEnrichedAtEQ(v time.Time) predicate.Artist {
	return predicate.Artist(sql.FieldEQ(FieldLastEnrichedAt, v))
}

// LastEnrichedAtNEQ applies the NEQ predicate on the "last_enriched_at" field.
func LastEnrichedAtNEQ(v time.Time) predicate.Artist {
	return predicate.Artist(sql.FieldNEQ(FieldLastEnrichedAt, v))
}

// LastEnrichedAtIn applies the In predicate on the "last_enriched_at" field.
func LastEnrichedAtIn(vs ...time.Time) predicate.Artist {
	return predicate.Artist(sql.FieldIn(FieldLastEnrichedAt, vs...))
}

// LastEnrichedAtNotIn applies the NotIn predicate on the "last_enriched_at" field.
func LastEnrichedAtNotIn(vs ...time.Time) predicate.Artist {
	return predicate.Artist(sql.FieldNotIn(FieldLastEnrichedAt, vs...))
}

// LastEnrichedAtGT applies the GT predicate on the "last_enriched_at" field.
func LastEnrichedAtGT(v time.Time) predicate.Artist {
	return predicate.Artist(sql.FieldGT(FieldLastEnrichedAt, v))
}

// LastEnrichedAtGTE applies the GTE predicate on the "last_enriched_at" field.
func LastEnrichedAtGTE(v time.Time) predicate.Artist {
	return predicate.Artist(sql.FieldGTE(FieldLastEnrichedAt, v))
}

// LastEnrichedAtLT applies the LT predicate on the "last_enriched_at" field.
func LastEnrichedAtLT(v time.Time) predicate.Artist {
	return predicate.Artist(sql.FieldLT(FieldLastEnrichedAt, v))
}

// LastEnrichedAtLTE applies the LTE predicate on the "last_enriched_at" field.
func LastEnrichedAtLTE(v time.Time) predicate.Artist {
	return predicate.Artist(sql.FieldLTE(FieldLastEnrichedAt, v))
}

// LastEnrichedAtIsNil applies the IsNil predicate on the "last_enriched_at" field.
func LastEnrichedAtIsNil() predicate.Artist {
	return predicate.Artist(sql.FieldIsNull(FieldLastEnrichedAt))
}

// LastEnrichedAtNotNil applies the NotNil predicate on the "last_enriched_at" field.
func LastEnrichedAtNotNil() predicate.Artist {
	return predicate.Artist(sql.FieldNotNull(FieldLastEnrichedAt))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Artist {
	return predicate.Artist(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Artist {
	return predicate.Artist(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAlbums applies the HasEdge predicate on the "albums" edge.
func HasAlbums() predicate.Artist {
	return predicate.Artist(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AlbumsTable, AlbumsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAlbumsWith applies the HasEdge predicate on the "albums" edge with a given conditions (other predicates).
func HasAlbumsWith(preds ...predicate.Album) predicate.Artist {
	return predicate.Artist(func(s *sql.Selector) {
		step := newAlbumsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTracks applies the HasEdge predicate on the "tracks" edge.
func HasTracks() predicate.Artist {
	return predicate.Artist(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TracksTable, TracksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTracksWith applies the HasEdge predicate on the "tracks" edge with a given conditions (other predicates).
func HasTracksWith(preds ...predicate.Track) predicate.Artist {
	return predicate.Artist(func(s *sql.Selector) {
		step := newTracksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasImages applies the HasEdge predicate on the "images" edge.
func HasImages() predicate.Artist {
	return predicate.Artist(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ImagesTable, ImagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasImagesWith applies the HasEdge predicate on the "images" edge with a given conditions (other predicates).
func HasImagesWith(preds ...predicate.ArtistImage) predicate.Artist {
	return predicate.Artist(func(s *sql.Selector) {
		step := newImagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasListens applies the HasEdge predicate on the "listens" edge.
func HasListens() predicate.Artist {
	return predicate.Artist(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ListensTable, ListensColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasListensWith applies the HasEdge predicate on the "listens" edge with a given conditions (other predicates).
func HasListensWith(preds ...predicate.Listen) predicate.Artist {
	return predicate.Artist(func(s *sql.Selector) {
		step := newListensStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Artist) predicate.Artist {
	return predicate.Artist(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Artist) predicate.Artist {
	return predicate.Artist(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Artist) predicate.Artist {
	return predicate.Artist(sql.NotPredicates(p))
}
