// Code generated by ent, DO NOT EDIT.

package artistimage

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the artistimage type in the database.
	Label = "artist_image"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldImageType holds the string denoting the image_type field in the database.
	FieldImageType = "image_type"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldLocalPath holds the string denoting the local_path field in the database.
	FieldLocalPath = "local_path"
	// FieldWidth holds the string denoting the width field in the database.
	FieldWidth = "width"
	// FieldHeight holds the string denoting the height field in the database.
	FieldHeight = "height"
	// FieldLikes holds the string denoting the likes field in the database.
	FieldLikes = "likes"
	// FieldIsPrimary holds the string denoting the is_primary field in the database.
	FieldIsPrimary = "is_primary"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeArtist holds the string denoting the artist edge name in mutations.
	EdgeArtist = "artist"
	// Table holds the table name of the artistimage in the database.
	Table = "artist_images"
	// ArtistTable is the table that holds the artist relation/edge.
	ArtistTable = "artist_images"
	// ArtistInverseTable is the table name for the Artist entity.
	// It exists in this package in order to avoid circular dependency with the "artist" package.
	ArtistInverseTable = "artists"
	// ArtistColumn is the table column denoting the artist relation/edge.
	ArtistColumn = "artist_images"
)

// Columns holds all SQL columns for artistimage fields.
var Columns = []string{
	FieldID,
	FieldImageType,
	FieldSource,
	FieldURL,
	FieldLocalPath,
	FieldWidth,
	FieldHeight,
	FieldLikes,
	FieldIsPrimary,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "artist_images"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"artist_images",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// SourceValidator is a validator for the "source" field. It is called by the builders before save.
	SourceValidator func(string) error
	// URLValidator is a validator for the "url" field. It is called by the builders before save.
	URLValidator func(string) error
	// DefaultIsPrimary holds the default value on creation for the "is_primary" field.
	DefaultIsPrimary bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// ImageType defines the type for the "image_type" enum field.
type ImageType string

// ImageType values.
const (
	ImageTypeThumbnail  ImageType = "thumbnail"
	ImageTypeBackground ImageType = "background"
	ImageTypeLogo       ImageType = "logo"
	ImageTypeBanner     ImageType = "banner"
	ImageTypeFanart     ImageType = "fanart"
)

func (it ImageType) String() string {
	return string(it)
}

// ImageTypeValidator is a validator for the "image_type" field enum values. It is called by the builders before save.
func ImageTypeValidator(it ImageType) error {
	switch it {
	case ImageTypeThumbnail, ImageTypeBackground, ImageTypeLogo, ImageTypeBanner, ImageTypeFanart:
		return nil
	default:
		return fmt.Errorf("artistimage: invalid enum value for image_type field: %q", it)
	}
}

// OrderOption defines the ordering options for the ArtistImage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByImageType orders the results by the image_type field.
func ByImageType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageType, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByLocalPath orders the results by the local_path field.
func ByLocalPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocalPath, opts...).ToFunc()
}

// ByWidth orders the results by the width field.
func ByWidth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWidth, opts...).ToFunc()
}

// ByHeight orders the results by the height field.
func ByHeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeight, opts...).ToFunc()
}

// ByLikes orders the results by the likes field.
func ByLikes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLikes, opts...).ToFunc()
}

// ByIsPrimary orders the results by the is_primary field.
func ByIsPrimary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsPrimary, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByArtistField orders the results by artist field.
func ByArtistField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newArtistStep(), sql.OrderByField(field, opts...))
	}
}
func newArtistStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ArtistInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ArtistTable, ArtistColumn),
	)
}
