// Code generated by ent, DO NOT EDIT.

package artistimage

import (
	"spotter/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldLTE(FieldID, id))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldEQ(FieldSource, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldEQ(FieldURL, v))
}

// LocalPath applies equality check predicate on the "local_path" field. It's identical to LocalPathEQ.
func LocalPath(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldEQ(FieldLocalPath, v))
}

// Width applies equality check predicate on the "width" field. It's identical to WidthEQ.
func Width(v int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldEQ(FieldWidth, v))
}

// Height applies equality check predicate on the "height" field. It's identical to HeightEQ.
func Height(v int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldEQ(FieldHeight, v))
}

// Likes applies equality check predicate on the "likes" field. It's identical to LikesEQ.
func Likes(v int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldEQ(FieldLikes, v))
}

// IsPrimary applies equality check predicate on the "is_primary" field. It's identical to IsPrimaryEQ.
func IsPrimary(v bool) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldEQ(FieldIsPrimary, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldEQ(FieldCreatedAt, v))
}

// ImageTypeEQ applies the EQ predicate on the "image_type" field.
func ImageTypeEQ(v ImageType) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldEQ(FieldImageType, v))
}

// ImageTypeNEQ applies the NEQ predicate on the "image_type" field.
func ImageTypeNEQ(v ImageType) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldNEQ(FieldImageType, v))
}

// ImageTypeIn applies the In predicate on the "image_type" field.
func ImageTypeIn(vs ...ImageType) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldIn(FieldImageType, vs...))
}

// ImageTypeNotIn applies the NotIn predicate on the "image_type" field.
func ImageTypeNotIn(vs ...ImageType) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldNotIn(FieldImageType, vs...))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldContainsFold(FieldSource, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldContainsFold(FieldURL, v))
}

// LocalPathEQ applies the EQ predicate on the "local_path" field.
func LocalPathEQ(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldEQ(FieldLocalPath, v))
}

// LocalPathNEQ applies the NEQ predicate on the "local_path" field.
func LocalPathNEQ(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldNEQ(FieldLocalPath, v))
}

// LocalPathIn applies the In predicate on the "local_path" field.
func LocalPathIn(vs ...string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldIn(FieldLocalPath, vs...))
}

// LocalPathNotIn applies the NotIn predicate on the "local_path" field.
func LocalPathNotIn(vs ...string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldNotIn(FieldLocalPath, vs...))
}

// LocalPathGT applies the GT predicate on the "local_path" field.
func LocalPathGT(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldGT(FieldLocalPath, v))
}

// LocalPathGTE applies the GTE predicate on the "local_path" field.
func LocalPathGTE(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldGTE(FieldLocalPath, v))
}

// LocalPathLT applies the LT predicate on the "local_path" field.
func LocalPathLT(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldLT(FieldLocalPath, v))
}

// LocalPathLTE applies the LTE predicate on the "local_path" field.
func LocalPathLTE(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldLTE(FieldLocalPath, v))
}

// LocalPathContains applies the Contains predicate on the "local_path" field.
func LocalPathContains(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldContains(FieldLocalPath, v))
}

// LocalPathHasPrefix applies the HasPrefix predicate on the "local_path" field.
func LocalPathHasPrefix(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldHasPrefix(FieldLocalPath, v))
}

// LocalPathHasSuffix applies the HasSuffix predicate on the "local_path" field.
func LocalPathHasSuffix(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldHasSuffix(FieldLocalPath, v))
}

// LocalPathIsNil applies the IsNil predicate on the "local_path" field.
func LocalPathIsNil() predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldIsNull(FieldLocalPath))
}

// LocalPathNotNil applies the NotNil predicate on the "local_path" field.
func LocalPathNotNil() predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldNotNull(FieldLocalPath))
}

// LocalPathEqualFold applies the EqualFold predicate on the "local_path" field.
func LocalPathEqualFold(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldEqualFold(FieldLocalPath, v))
}

// LocalPathContainsFold applies the ContainsFold predicate on the "local_path" field.
func LocalPathContainsFold(v string) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldContainsFold(FieldLocalPath, v))
}

// WidthEQ applies the EQ predicate on the "width" field.
func WidthEQ(v int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldEQ(FieldWidth, v))
}

// WidthNEQ applies the NEQ predicate on the "width" field.
func WidthNEQ(v int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldNEQ(FieldWidth, v))
}

// WidthIn applies the In predicate on the "width" field.
func WidthIn(vs ...int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldIn(FieldWidth, vs...))
}

// WidthNotIn applies the NotIn predicate on the "width" field.
func WidthNotIn(vs ...int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldNotIn(FieldWidth, vs...))
}

// WidthGT applies the GT predicate on the "width" field.
func WidthGT(v int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldGT(FieldWidth, v))
}

// WidthGTE applies the GTE predicate on the "width" field.
func WidthGTE(v int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldGTE(FieldWidth, v))
}

// WidthLT applies the LT predicate on the "width" field.
func WidthLT(v int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldLT(FieldWidth, v))
}

// WidthLTE applies the LTE predicate on the "width" field.
func WidthLTE(v int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldLTE(FieldWidth, v))
}

// WidthIsNil applies the IsNil predicate on the "width" field.
func WidthIsNil() predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldIsNull(FieldWidth))
}

// WidthNotNil applies the NotNil predicate on the "width" field.
func WidthNotNil() predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldNotNull(FieldWidth))
}

// HeightEQ applies the EQ predicate on the "height" field.
func HeightEQ(v int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldEQ(FieldHeight, v))
}

// HeightNEQ applies the NEQ predicate on the "height" field.
func HeightNEQ(v int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldNEQ(FieldHeight, v))
}

// HeightIn applies the In predicate on the "height" field.
func HeightIn(vs ...int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldIn(FieldHeight, vs...))
}

// HeightNotIn applies the NotIn predicate on the "height" field.
func HeightNotIn(vs ...int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldNotIn(FieldHeight, vs...))
}

// HeightGT applies the GT predicate on the "height" field.
func HeightGT(v int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldGT(FieldHeight, v))
}

// HeightGTE applies the GTE predicate on the "height" field.
func HeightGTE(v int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldGTE(FieldHeight, v))
}

// HeightLT applies the LT predicate on the "height" field.
func HeightLT(v int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldLT(FieldHeight, v))
}

// HeightLTE applies the LTE predicate on the "height" field.
func HeightLTE(v int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldLTE(FieldHeight, v))
}

// HeightIsNil applies the IsNil predicate on the "height" field.
func HeightIsNil() predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldIsNull(FieldHeight))
}

// HeightNotNil applies the NotNil predicate on the "height" field.
func HeightNotNil() predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldNotNull(FieldHeight))
}

// LikesEQ applies the EQ predicate on the "likes" field.
func LikesEQ(v int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldEQ(FieldLikes, v))
}

// LikesNEQ applies the NEQ predicate on the "likes" field.
func LikesNEQ(v int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldNEQ(FieldLikes, v))
}

// LikesIn applies the In predicate on the "likes" field.
func LikesIn(vs ...int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldIn(FieldLikes, vs...))
}

// LikesNotIn applies the NotIn predicate on the "likes" field.
func LikesNotIn(vs ...int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldNotIn(FieldLikes, vs...))
}

// LikesGT applies the GT predicate on the "likes" field.
func LikesGT(v int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldGT(FieldLikes, v))
}

// LikesGTE applies the GTE predicate on the "likes" field.
func LikesGTE(v int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldGTE(FieldLikes, v))
}

// LikesLT applies the LT predicate on the "likes" field.
func LikesLT(v int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldLT(FieldLikes, v))
}

// LikesLTE applies the LTE predicate on the "likes" field.
func LikesLTE(v int) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldLTE(FieldLikes, v))
}

// LikesIsNil applies the IsNil predicate on the "likes" field.
func LikesIsNil() predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldIsNull(FieldLikes))
}

// LikesNotNil applies the NotNil predicate on the "likes" field.
func LikesNotNil() predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldNotNull(FieldLikes))
}

// IsPrimaryEQ applies the EQ predicate on the "is_primary" field.
func IsPrimaryEQ(v bool) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldEQ(FieldIsPrimary, v))
}

// IsPrimaryNEQ applies the NEQ predicate on the "is_primary" field.
func IsPrimaryNEQ(v bool) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldNEQ(FieldIsPrimary, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ArtistImage {
	return predicate.ArtistImage(sql.FieldLTE(FieldCreatedAt, v))
}

// HasArtist applies the HasEdge predicate on the "artist" edge.
func HasArtist() predicate.ArtistImage {
	return predicate.ArtistImage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ArtistTable, ArtistColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasArtistWith applies the HasEdge predicate on the "artist" edge with a given conditions (other predicates).
func HasArtistWith(preds ...predicate.Artist) predicate.ArtistImage {
	return predicate.ArtistImage(func(s *sql.Selector) {
		step := newArtistStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ArtistImage) predicate.ArtistImage {
	return predicate.ArtistImage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ArtistImage) predicate.ArtistImage {
	return predicate.ArtistImage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ArtistImage) predicate.ArtistImage {
	return predicate.ArtistImage(sql.NotPredicates(p))
}
