package schema

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
)

// Mixtape holds the schema definition for the Mixtape entity.
type Mixtape struct {
	ent.Schema
}

// Fields of the Mixtape.
func (Mixtape) Fields() []ent.Field {
	return []ent.Field{
		field.String("name").
			NotEmpty().
			Comment("User-given name for this mixtape"),
		field.String("description").
			Optional().
			Comment("Optional description of the mixtape"),
		field.String("image_url").
			Optional().
			Comment("URL to the mixtape cover art"),
		field.Enum("schedule").
			Values("none", "daily", "weekly", "monthly").
			Default("none").
			Comment("How often to regenerate the mixtape"),
		field.Bool("sync_to_navidrome").
			Default(false).
			Comment("Whether to sync this mixtape as a playlist in Navidrome"),
		field.String("navidrome_playlist_id").
			Optional().
			Comment("The remote playlist ID in Navidrome if synced"),
		field.Int("track_count").
			Default(0).
			Comment("Number of tracks in the mixtape"),
		field.Int("max_tracks").
			Default(25).
			Comment("Maximum number of tracks the AI should generate"),
		field.Strings("track_ids").
			Optional().
			Comment("IDs of tracks in this mixtape"),
		field.Text("generation_prompt").
			Optional().
			Comment("The full prompt sent to the AI for debugging and reproducibility"),
		field.Int("generation_tokens_used").
			Optional().
			Nillable().
			Comment("Number of tokens used in the last generation"),
		field.String("generation_model").
			Optional().
			Comment("The AI model used for the last generation"),
		field.String("generation_error").
			Optional().
			Comment("Error message from the last generation attempt, empty if successful"),
		field.String("seed_type").
			Optional().
			Comment("Type of seed data used: artist, album, tracks, or empty for DJ-only"),
		field.Int("seed_id").
			Optional().
			Nillable().
			Comment("ID of the seed entity (artist or album ID)"),
		field.Strings("seed_track_ids").
			Optional().
			Comment("Track IDs if seeded with specific tracks"),
		field.Time("last_generated_at").
			Optional().
			Nillable().
			Comment("When the mixtape was last generated by AI"),
		field.Time("created_at").
			Default(time.Now).
			Immutable(),
		field.Time("updated_at").
			Default(time.Now).
			UpdateDefault(time.Now),
	}
}

// Edges of the Mixtape.
func (Mixtape) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("user", User.Type).
			Ref("mixtapes").
			Unique().
			Required(),
		edge.From("dj", DJ.Type).
			Ref("mixtapes").
			Unique().
			Required(),
	}
}

// Indexes of the Mixtape.
func (Mixtape) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("name").
			Edges("user").
			Unique(),
	}
}
