// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"spotter/ent/album"
	"spotter/ent/albumimage"
	"spotter/ent/artist"
	"spotter/ent/listen"
	"spotter/ent/predicate"
	"spotter/ent/track"
	"spotter/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// AlbumUpdate is the builder for updating Album entities.
type AlbumUpdate struct {
	config
	hooks    []Hook
	mutation *AlbumMutation
}

// Where appends a list predicates to the AlbumUpdate builder.
func (_u *AlbumUpdate) Where(ps ...predicate.Album) *AlbumUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *AlbumUpdate) SetName(v string) *AlbumUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AlbumUpdate) SetNillableName(v *string) *AlbumUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSortName sets the "sort_name" field.
func (_u *AlbumUpdate) SetSortName(v string) *AlbumUpdate {
	_u.mutation.SetSortName(v)
	return _u
}

// SetNillableSortName sets the "sort_name" field if the given value is not nil.
func (_u *AlbumUpdate) SetNillableSortName(v *string) *AlbumUpdate {
	if v != nil {
		_u.SetSortName(*v)
	}
	return _u
}

// ClearSortName clears the value of the "sort_name" field.
func (_u *AlbumUpdate) ClearSortName() *AlbumUpdate {
	_u.mutation.ClearSortName()
	return _u
}

// SetMusicbrainzID sets the "musicbrainz_id" field.
func (_u *AlbumUpdate) SetMusicbrainzID(v string) *AlbumUpdate {
	_u.mutation.SetMusicbrainzID(v)
	return _u
}

// SetNillableMusicbrainzID sets the "musicbrainz_id" field if the given value is not nil.
func (_u *AlbumUpdate) SetNillableMusicbrainzID(v *string) *AlbumUpdate {
	if v != nil {
		_u.SetMusicbrainzID(*v)
	}
	return _u
}

// ClearMusicbrainzID clears the value of the "musicbrainz_id" field.
func (_u *AlbumUpdate) ClearMusicbrainzID() *AlbumUpdate {
	_u.mutation.ClearMusicbrainzID()
	return _u
}

// SetSpotifyID sets the "spotify_id" field.
func (_u *AlbumUpdate) SetSpotifyID(v string) *AlbumUpdate {
	_u.mutation.SetSpotifyID(v)
	return _u
}

// SetNillableSpotifyID sets the "spotify_id" field if the given value is not nil.
func (_u *AlbumUpdate) SetNillableSpotifyID(v *string) *AlbumUpdate {
	if v != nil {
		_u.SetSpotifyID(*v)
	}
	return _u
}

// ClearSpotifyID clears the value of the "spotify_id" field.
func (_u *AlbumUpdate) ClearSpotifyID() *AlbumUpdate {
	_u.mutation.ClearSpotifyID()
	return _u
}

// SetReleaseDate sets the "release_date" field.
func (_u *AlbumUpdate) SetReleaseDate(v string) *AlbumUpdate {
	_u.mutation.SetReleaseDate(v)
	return _u
}

// SetNillableReleaseDate sets the "release_date" field if the given value is not nil.
func (_u *AlbumUpdate) SetNillableReleaseDate(v *string) *AlbumUpdate {
	if v != nil {
		_u.SetReleaseDate(*v)
	}
	return _u
}

// ClearReleaseDate clears the value of the "release_date" field.
func (_u *AlbumUpdate) ClearReleaseDate() *AlbumUpdate {
	_u.mutation.ClearReleaseDate()
	return _u
}

// SetYear sets the "year" field.
func (_u *AlbumUpdate) SetYear(v int) *AlbumUpdate {
	_u.mutation.ResetYear()
	_u.mutation.SetYear(v)
	return _u
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (_u *AlbumUpdate) SetNillableYear(v *int) *AlbumUpdate {
	if v != nil {
		_u.SetYear(*v)
	}
	return _u
}

// AddYear adds value to the "year" field.
func (_u *AlbumUpdate) AddYear(v int) *AlbumUpdate {
	_u.mutation.AddYear(v)
	return _u
}

// ClearYear clears the value of the "year" field.
func (_u *AlbumUpdate) ClearYear() *AlbumUpdate {
	_u.mutation.ClearYear()
	return _u
}

// SetGenre sets the "genre" field.
func (_u *AlbumUpdate) SetGenre(v string) *AlbumUpdate {
	_u.mutation.SetGenre(v)
	return _u
}

// SetNillableGenre sets the "genre" field if the given value is not nil.
func (_u *AlbumUpdate) SetNillableGenre(v *string) *AlbumUpdate {
	if v != nil {
		_u.SetGenre(*v)
	}
	return _u
}

// ClearGenre clears the value of the "genre" field.
func (_u *AlbumUpdate) ClearGenre() *AlbumUpdate {
	_u.mutation.ClearGenre()
	return _u
}

// SetTags sets the "tags" field.
func (_u *AlbumUpdate) SetTags(v []string) *AlbumUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *AlbumUpdate) AppendTags(v []string) *AlbumUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *AlbumUpdate) ClearTags() *AlbumUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetPopularity sets the "popularity" field.
func (_u *AlbumUpdate) SetPopularity(v int) *AlbumUpdate {
	_u.mutation.ResetPopularity()
	_u.mutation.SetPopularity(v)
	return _u
}

// SetNillablePopularity sets the "popularity" field if the given value is not nil.
func (_u *AlbumUpdate) SetNillablePopularity(v *int) *AlbumUpdate {
	if v != nil {
		_u.SetPopularity(*v)
	}
	return _u
}

// AddPopularity adds value to the "popularity" field.
func (_u *AlbumUpdate) AddPopularity(v int) *AlbumUpdate {
	_u.mutation.AddPopularity(v)
	return _u
}

// ClearPopularity clears the value of the "popularity" field.
func (_u *AlbumUpdate) ClearPopularity() *AlbumUpdate {
	_u.mutation.ClearPopularity()
	return _u
}

// SetTotalTracks sets the "total_tracks" field.
func (_u *AlbumUpdate) SetTotalTracks(v int) *AlbumUpdate {
	_u.mutation.ResetTotalTracks()
	_u.mutation.SetTotalTracks(v)
	return _u
}

// SetNillableTotalTracks sets the "total_tracks" field if the given value is not nil.
func (_u *AlbumUpdate) SetNillableTotalTracks(v *int) *AlbumUpdate {
	if v != nil {
		_u.SetTotalTracks(*v)
	}
	return _u
}

// AddTotalTracks adds value to the "total_tracks" field.
func (_u *AlbumUpdate) AddTotalTracks(v int) *AlbumUpdate {
	_u.mutation.AddTotalTracks(v)
	return _u
}

// ClearTotalTracks clears the value of the "total_tracks" field.
func (_u *AlbumUpdate) ClearTotalTracks() *AlbumUpdate {
	_u.mutation.ClearTotalTracks()
	return _u
}

// SetAlbumType sets the "album_type" field.
func (_u *AlbumUpdate) SetAlbumType(v string) *AlbumUpdate {
	_u.mutation.SetAlbumType(v)
	return _u
}

// SetNillableAlbumType sets the "album_type" field if the given value is not nil.
func (_u *AlbumUpdate) SetNillableAlbumType(v *string) *AlbumUpdate {
	if v != nil {
		_u.SetAlbumType(*v)
	}
	return _u
}

// ClearAlbumType clears the value of the "album_type" field.
func (_u *AlbumUpdate) ClearAlbumType() *AlbumUpdate {
	_u.mutation.ClearAlbumType()
	return _u
}

// SetLabel sets the "label" field.
func (_u *AlbumUpdate) SetLabel(v string) *AlbumUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *AlbumUpdate) SetNillableLabel(v *string) *AlbumUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// ClearLabel clears the value of the "label" field.
func (_u *AlbumUpdate) ClearLabel() *AlbumUpdate {
	_u.mutation.ClearLabel()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AlbumUpdate) SetUpdatedAt(v time.Time) *AlbumUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLastEnrichedAt sets the "last_enriched_at" field.
func (_u *AlbumUpdate) SetLastEnrichedAt(v time.Time) *AlbumUpdate {
	_u.mutation.SetLastEnrichedAt(v)
	return _u
}

// SetNillableLastEnrichedAt sets the "last_enriched_at" field if the given value is not nil.
func (_u *AlbumUpdate) SetNillableLastEnrichedAt(v *time.Time) *AlbumUpdate {
	if v != nil {
		_u.SetLastEnrichedAt(*v)
	}
	return _u
}

// ClearLastEnrichedAt clears the value of the "last_enriched_at" field.
func (_u *AlbumUpdate) ClearLastEnrichedAt() *AlbumUpdate {
	_u.mutation.ClearLastEnrichedAt()
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *AlbumUpdate) SetUserID(id int) *AlbumUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AlbumUpdate) SetUser(v *User) *AlbumUpdate {
	return _u.SetUserID(v.ID)
}

// SetArtistID sets the "artist" edge to the Artist entity by ID.
func (_u *AlbumUpdate) SetArtistID(id int) *AlbumUpdate {
	_u.mutation.SetArtistID(id)
	return _u
}

// SetNillableArtistID sets the "artist" edge to the Artist entity by ID if the given value is not nil.
func (_u *AlbumUpdate) SetNillableArtistID(id *int) *AlbumUpdate {
	if id != nil {
		_u = _u.SetArtistID(*id)
	}
	return _u
}

// SetArtist sets the "artist" edge to the Artist entity.
func (_u *AlbumUpdate) SetArtist(v *Artist) *AlbumUpdate {
	return _u.SetArtistID(v.ID)
}

// AddTrackIDs adds the "tracks" edge to the Track entity by IDs.
func (_u *AlbumUpdate) AddTrackIDs(ids ...int) *AlbumUpdate {
	_u.mutation.AddTrackIDs(ids...)
	return _u
}

// AddTracks adds the "tracks" edges to the Track entity.
func (_u *AlbumUpdate) AddTracks(v ...*Track) *AlbumUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTrackIDs(ids...)
}

// AddImageIDs adds the "images" edge to the AlbumImage entity by IDs.
func (_u *AlbumUpdate) AddImageIDs(ids ...int) *AlbumUpdate {
	_u.mutation.AddImageIDs(ids...)
	return _u
}

// AddImages adds the "images" edges to the AlbumImage entity.
func (_u *AlbumUpdate) AddImages(v ...*AlbumImage) *AlbumUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddImageIDs(ids...)
}

// AddListenIDs adds the "listens" edge to the Listen entity by IDs.
func (_u *AlbumUpdate) AddListenIDs(ids ...int) *AlbumUpdate {
	_u.mutation.AddListenIDs(ids...)
	return _u
}

// AddListens adds the "listens" edges to the Listen entity.
func (_u *AlbumUpdate) AddListens(v ...*Listen) *AlbumUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddListenIDs(ids...)
}

// Mutation returns the AlbumMutation object of the builder.
func (_u *AlbumUpdate) Mutation() *AlbumMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AlbumUpdate) ClearUser() *AlbumUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearArtist clears the "artist" edge to the Artist entity.
func (_u *AlbumUpdate) ClearArtist() *AlbumUpdate {
	_u.mutation.ClearArtist()
	return _u
}

// ClearTracks clears all "tracks" edges to the Track entity.
func (_u *AlbumUpdate) ClearTracks() *AlbumUpdate {
	_u.mutation.ClearTracks()
	return _u
}

// RemoveTrackIDs removes the "tracks" edge to Track entities by IDs.
func (_u *AlbumUpdate) RemoveTrackIDs(ids ...int) *AlbumUpdate {
	_u.mutation.RemoveTrackIDs(ids...)
	return _u
}

// RemoveTracks removes "tracks" edges to Track entities.
func (_u *AlbumUpdate) RemoveTracks(v ...*Track) *AlbumUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTrackIDs(ids...)
}

// ClearImages clears all "images" edges to the AlbumImage entity.
func (_u *AlbumUpdate) ClearImages() *AlbumUpdate {
	_u.mutation.ClearImages()
	return _u
}

// RemoveImageIDs removes the "images" edge to AlbumImage entities by IDs.
func (_u *AlbumUpdate) RemoveImageIDs(ids ...int) *AlbumUpdate {
	_u.mutation.RemoveImageIDs(ids...)
	return _u
}

// RemoveImages removes "images" edges to AlbumImage entities.
func (_u *AlbumUpdate) RemoveImages(v ...*AlbumImage) *AlbumUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveImageIDs(ids...)
}

// ClearListens clears all "listens" edges to the Listen entity.
func (_u *AlbumUpdate) ClearListens() *AlbumUpdate {
	_u.mutation.ClearListens()
	return _u
}

// RemoveListenIDs removes the "listens" edge to Listen entities by IDs.
func (_u *AlbumUpdate) RemoveListenIDs(ids ...int) *AlbumUpdate {
	_u.mutation.RemoveListenIDs(ids...)
	return _u
}

// RemoveListens removes "listens" edges to Listen entities.
func (_u *AlbumUpdate) RemoveListens(v ...*Listen) *AlbumUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveListenIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AlbumUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AlbumUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AlbumUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AlbumUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AlbumUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := album.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AlbumUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := album.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Album.name": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Album.user"`)
	}
	return nil
}

func (_u *AlbumUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(album.Table, album.Columns, sqlgraph.NewFieldSpec(album.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(album.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortName(); ok {
		_spec.SetField(album.FieldSortName, field.TypeString, value)
	}
	if _u.mutation.SortNameCleared() {
		_spec.ClearField(album.FieldSortName, field.TypeString)
	}
	if value, ok := _u.mutation.MusicbrainzID(); ok {
		_spec.SetField(album.FieldMusicbrainzID, field.TypeString, value)
	}
	if _u.mutation.MusicbrainzIDCleared() {
		_spec.ClearField(album.FieldMusicbrainzID, field.TypeString)
	}
	if value, ok := _u.mutation.SpotifyID(); ok {
		_spec.SetField(album.FieldSpotifyID, field.TypeString, value)
	}
	if _u.mutation.SpotifyIDCleared() {
		_spec.ClearField(album.FieldSpotifyID, field.TypeString)
	}
	if value, ok := _u.mutation.ReleaseDate(); ok {
		_spec.SetField(album.FieldReleaseDate, field.TypeString, value)
	}
	if _u.mutation.ReleaseDateCleared() {
		_spec.ClearField(album.FieldReleaseDate, field.TypeString)
	}
	if value, ok := _u.mutation.Year(); ok {
		_spec.SetField(album.FieldYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedYear(); ok {
		_spec.AddField(album.FieldYear, field.TypeInt, value)
	}
	if _u.mutation.YearCleared() {
		_spec.ClearField(album.FieldYear, field.TypeInt)
	}
	if value, ok := _u.mutation.Genre(); ok {
		_spec.SetField(album.FieldGenre, field.TypeString, value)
	}
	if _u.mutation.GenreCleared() {
		_spec.ClearField(album.FieldGenre, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(album.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, album.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(album.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.Popularity(); ok {
		_spec.SetField(album.FieldPopularity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPopularity(); ok {
		_spec.AddField(album.FieldPopularity, field.TypeInt, value)
	}
	if _u.mutation.PopularityCleared() {
		_spec.ClearField(album.FieldPopularity, field.TypeInt)
	}
	if value, ok := _u.mutation.TotalTracks(); ok {
		_spec.SetField(album.FieldTotalTracks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalTracks(); ok {
		_spec.AddField(album.FieldTotalTracks, field.TypeInt, value)
	}
	if _u.mutation.TotalTracksCleared() {
		_spec.ClearField(album.FieldTotalTracks, field.TypeInt)
	}
	if value, ok := _u.mutation.AlbumType(); ok {
		_spec.SetField(album.FieldAlbumType, field.TypeString, value)
	}
	if _u.mutation.AlbumTypeCleared() {
		_spec.ClearField(album.FieldAlbumType, field.TypeString)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(album.FieldLabel, field.TypeString, value)
	}
	if _u.mutation.LabelCleared() {
		_spec.ClearField(album.FieldLabel, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(album.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastEnrichedAt(); ok {
		_spec.SetField(album.FieldLastEnrichedAt, field.TypeTime, value)
	}
	if _u.mutation.LastEnrichedAtCleared() {
		_spec.ClearField(album.FieldLastEnrichedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   album.UserTable,
			Columns: []string{album.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   album.UserTable,
			Columns: []string{album.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ArtistCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   album.ArtistTable,
			Columns: []string{album.ArtistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArtistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   album.ArtistTable,
			Columns: []string{album.ArtistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TracksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   album.TracksTable,
			Columns: []string{album.TracksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(track.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTracksIDs(); len(nodes) > 0 && !_u.mutation.TracksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   album.TracksTable,
			Columns: []string{album.TracksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(track.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TracksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   album.TracksTable,
			Columns: []string{album.TracksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(track.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ImagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   album.ImagesTable,
			Columns: []string{album.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(albumimage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedImagesIDs(); len(nodes) > 0 && !_u.mutation.ImagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   album.ImagesTable,
			Columns: []string{album.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(albumimage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ImagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   album.ImagesTable,
			Columns: []string{album.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(albumimage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ListensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   album.ListensTable,
			Columns: []string{album.ListensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listen.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedListensIDs(); len(nodes) > 0 && !_u.mutation.ListensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   album.ListensTable,
			Columns: []string{album.ListensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listen.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ListensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   album.ListensTable,
			Columns: []string{album.ListensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listen.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{album.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AlbumUpdateOne is the builder for updating a single Album entity.
type AlbumUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AlbumMutation
}

// SetName sets the "name" field.
func (_u *AlbumUpdateOne) SetName(v string) *AlbumUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AlbumUpdateOne) SetNillableName(v *string) *AlbumUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSortName sets the "sort_name" field.
func (_u *AlbumUpdateOne) SetSortName(v string) *AlbumUpdateOne {
	_u.mutation.SetSortName(v)
	return _u
}

// SetNillableSortName sets the "sort_name" field if the given value is not nil.
func (_u *AlbumUpdateOne) SetNillableSortName(v *string) *AlbumUpdateOne {
	if v != nil {
		_u.SetSortName(*v)
	}
	return _u
}

// ClearSortName clears the value of the "sort_name" field.
func (_u *AlbumUpdateOne) ClearSortName() *AlbumUpdateOne {
	_u.mutation.ClearSortName()
	return _u
}

// SetMusicbrainzID sets the "musicbrainz_id" field.
func (_u *AlbumUpdateOne) SetMusicbrainzID(v string) *AlbumUpdateOne {
	_u.mutation.SetMusicbrainzID(v)
	return _u
}

// SetNillableMusicbrainzID sets the "musicbrainz_id" field if the given value is not nil.
func (_u *AlbumUpdateOne) SetNillableMusicbrainzID(v *string) *AlbumUpdateOne {
	if v != nil {
		_u.SetMusicbrainzID(*v)
	}
	return _u
}

// ClearMusicbrainzID clears the value of the "musicbrainz_id" field.
func (_u *AlbumUpdateOne) ClearMusicbrainzID() *AlbumUpdateOne {
	_u.mutation.ClearMusicbrainzID()
	return _u
}

// SetSpotifyID sets the "spotify_id" field.
func (_u *AlbumUpdateOne) SetSpotifyID(v string) *AlbumUpdateOne {
	_u.mutation.SetSpotifyID(v)
	return _u
}

// SetNillableSpotifyID sets the "spotify_id" field if the given value is not nil.
func (_u *AlbumUpdateOne) SetNillableSpotifyID(v *string) *AlbumUpdateOne {
	if v != nil {
		_u.SetSpotifyID(*v)
	}
	return _u
}

// ClearSpotifyID clears the value of the "spotify_id" field.
func (_u *AlbumUpdateOne) ClearSpotifyID() *AlbumUpdateOne {
	_u.mutation.ClearSpotifyID()
	return _u
}

// SetReleaseDate sets the "release_date" field.
func (_u *AlbumUpdateOne) SetReleaseDate(v string) *AlbumUpdateOne {
	_u.mutation.SetReleaseDate(v)
	return _u
}

// SetNillableReleaseDate sets the "release_date" field if the given value is not nil.
func (_u *AlbumUpdateOne) SetNillableReleaseDate(v *string) *AlbumUpdateOne {
	if v != nil {
		_u.SetReleaseDate(*v)
	}
	return _u
}

// ClearReleaseDate clears the value of the "release_date" field.
func (_u *AlbumUpdateOne) ClearReleaseDate() *AlbumUpdateOne {
	_u.mutation.ClearReleaseDate()
	return _u
}

// SetYear sets the "year" field.
func (_u *AlbumUpdateOne) SetYear(v int) *AlbumUpdateOne {
	_u.mutation.ResetYear()
	_u.mutation.SetYear(v)
	return _u
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (_u *AlbumUpdateOne) SetNillableYear(v *int) *AlbumUpdateOne {
	if v != nil {
		_u.SetYear(*v)
	}
	return _u
}

// AddYear adds value to the "year" field.
func (_u *AlbumUpdateOne) AddYear(v int) *AlbumUpdateOne {
	_u.mutation.AddYear(v)
	return _u
}

// ClearYear clears the value of the "year" field.
func (_u *AlbumUpdateOne) ClearYear() *AlbumUpdateOne {
	_u.mutation.ClearYear()
	return _u
}

// SetGenre sets the "genre" field.
func (_u *AlbumUpdateOne) SetGenre(v string) *AlbumUpdateOne {
	_u.mutation.SetGenre(v)
	return _u
}

// SetNillableGenre sets the "genre" field if the given value is not nil.
func (_u *AlbumUpdateOne) SetNillableGenre(v *string) *AlbumUpdateOne {
	if v != nil {
		_u.SetGenre(*v)
	}
	return _u
}

// ClearGenre clears the value of the "genre" field.
func (_u *AlbumUpdateOne) ClearGenre() *AlbumUpdateOne {
	_u.mutation.ClearGenre()
	return _u
}

// SetTags sets the "tags" field.
func (_u *AlbumUpdateOne) SetTags(v []string) *AlbumUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *AlbumUpdateOne) AppendTags(v []string) *AlbumUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *AlbumUpdateOne) ClearTags() *AlbumUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetPopularity sets the "popularity" field.
func (_u *AlbumUpdateOne) SetPopularity(v int) *AlbumUpdateOne {
	_u.mutation.ResetPopularity()
	_u.mutation.SetPopularity(v)
	return _u
}

// SetNillablePopularity sets the "popularity" field if the given value is not nil.
func (_u *AlbumUpdateOne) SetNillablePopularity(v *int) *AlbumUpdateOne {
	if v != nil {
		_u.SetPopularity(*v)
	}
	return _u
}

// AddPopularity adds value to the "popularity" field.
func (_u *AlbumUpdateOne) AddPopularity(v int) *AlbumUpdateOne {
	_u.mutation.AddPopularity(v)
	return _u
}

// ClearPopularity clears the value of the "popularity" field.
func (_u *AlbumUpdateOne) ClearPopularity() *AlbumUpdateOne {
	_u.mutation.ClearPopularity()
	return _u
}

// SetTotalTracks sets the "total_tracks" field.
func (_u *AlbumUpdateOne) SetTotalTracks(v int) *AlbumUpdateOne {
	_u.mutation.ResetTotalTracks()
	_u.mutation.SetTotalTracks(v)
	return _u
}

// SetNillableTotalTracks sets the "total_tracks" field if the given value is not nil.
func (_u *AlbumUpdateOne) SetNillableTotalTracks(v *int) *AlbumUpdateOne {
	if v != nil {
		_u.SetTotalTracks(*v)
	}
	return _u
}

// AddTotalTracks adds value to the "total_tracks" field.
func (_u *AlbumUpdateOne) AddTotalTracks(v int) *AlbumUpdateOne {
	_u.mutation.AddTotalTracks(v)
	return _u
}

// ClearTotalTracks clears the value of the "total_tracks" field.
func (_u *AlbumUpdateOne) ClearTotalTracks() *AlbumUpdateOne {
	_u.mutation.ClearTotalTracks()
	return _u
}

// SetAlbumType sets the "album_type" field.
func (_u *AlbumUpdateOne) SetAlbumType(v string) *AlbumUpdateOne {
	_u.mutation.SetAlbumType(v)
	return _u
}

// SetNillableAlbumType sets the "album_type" field if the given value is not nil.
func (_u *AlbumUpdateOne) SetNillableAlbumType(v *string) *AlbumUpdateOne {
	if v != nil {
		_u.SetAlbumType(*v)
	}
	return _u
}

// ClearAlbumType clears the value of the "album_type" field.
func (_u *AlbumUpdateOne) ClearAlbumType() *AlbumUpdateOne {
	_u.mutation.ClearAlbumType()
	return _u
}

// SetLabel sets the "label" field.
func (_u *AlbumUpdateOne) SetLabel(v string) *AlbumUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *AlbumUpdateOne) SetNillableLabel(v *string) *AlbumUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// ClearLabel clears the value of the "label" field.
func (_u *AlbumUpdateOne) ClearLabel() *AlbumUpdateOne {
	_u.mutation.ClearLabel()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AlbumUpdateOne) SetUpdatedAt(v time.Time) *AlbumUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLastEnrichedAt sets the "last_enriched_at" field.
func (_u *AlbumUpdateOne) SetLastEnrichedAt(v time.Time) *AlbumUpdateOne {
	_u.mutation.SetLastEnrichedAt(v)
	return _u
}

// SetNillableLastEnrichedAt sets the "last_enriched_at" field if the given value is not nil.
func (_u *AlbumUpdateOne) SetNillableLastEnrichedAt(v *time.Time) *AlbumUpdateOne {
	if v != nil {
		_u.SetLastEnrichedAt(*v)
	}
	return _u
}

// ClearLastEnrichedAt clears the value of the "last_enriched_at" field.
func (_u *AlbumUpdateOne) ClearLastEnrichedAt() *AlbumUpdateOne {
	_u.mutation.ClearLastEnrichedAt()
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *AlbumUpdateOne) SetUserID(id int) *AlbumUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AlbumUpdateOne) SetUser(v *User) *AlbumUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetArtistID sets the "artist" edge to the Artist entity by ID.
func (_u *AlbumUpdateOne) SetArtistID(id int) *AlbumUpdateOne {
	_u.mutation.SetArtistID(id)
	return _u
}

// SetNillableArtistID sets the "artist" edge to the Artist entity by ID if the given value is not nil.
func (_u *AlbumUpdateOne) SetNillableArtistID(id *int) *AlbumUpdateOne {
	if id != nil {
		_u = _u.SetArtistID(*id)
	}
	return _u
}

// SetArtist sets the "artist" edge to the Artist entity.
func (_u *AlbumUpdateOne) SetArtist(v *Artist) *AlbumUpdateOne {
	return _u.SetArtistID(v.ID)
}

// AddTrackIDs adds the "tracks" edge to the Track entity by IDs.
func (_u *AlbumUpdateOne) AddTrackIDs(ids ...int) *AlbumUpdateOne {
	_u.mutation.AddTrackIDs(ids...)
	return _u
}

// AddTracks adds the "tracks" edges to the Track entity.
func (_u *AlbumUpdateOne) AddTracks(v ...*Track) *AlbumUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTrackIDs(ids...)
}

// AddImageIDs adds the "images" edge to the AlbumImage entity by IDs.
func (_u *AlbumUpdateOne) AddImageIDs(ids ...int) *AlbumUpdateOne {
	_u.mutation.AddImageIDs(ids...)
	return _u
}

// AddImages adds the "images" edges to the AlbumImage entity.
func (_u *AlbumUpdateOne) AddImages(v ...*AlbumImage) *AlbumUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddImageIDs(ids...)
}

// AddListenIDs adds the "listens" edge to the Listen entity by IDs.
func (_u *AlbumUpdateOne) AddListenIDs(ids ...int) *AlbumUpdateOne {
	_u.mutation.AddListenIDs(ids...)
	return _u
}

// AddListens adds the "listens" edges to the Listen entity.
func (_u *AlbumUpdateOne) AddListens(v ...*Listen) *AlbumUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddListenIDs(ids...)
}

// Mutation returns the AlbumMutation object of the builder.
func (_u *AlbumUpdateOne) Mutation() *AlbumMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AlbumUpdateOne) ClearUser() *AlbumUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearArtist clears the "artist" edge to the Artist entity.
func (_u *AlbumUpdateOne) ClearArtist() *AlbumUpdateOne {
	_u.mutation.ClearArtist()
	return _u
}

// ClearTracks clears all "tracks" edges to the Track entity.
func (_u *AlbumUpdateOne) ClearTracks() *AlbumUpdateOne {
	_u.mutation.ClearTracks()
	return _u
}

// RemoveTrackIDs removes the "tracks" edge to Track entities by IDs.
func (_u *AlbumUpdateOne) RemoveTrackIDs(ids ...int) *AlbumUpdateOne {
	_u.mutation.RemoveTrackIDs(ids...)
	return _u
}

// RemoveTracks removes "tracks" edges to Track entities.
func (_u *AlbumUpdateOne) RemoveTracks(v ...*Track) *AlbumUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTrackIDs(ids...)
}

// ClearImages clears all "images" edges to the AlbumImage entity.
func (_u *AlbumUpdateOne) ClearImages() *AlbumUpdateOne {
	_u.mutation.ClearImages()
	return _u
}

// RemoveImageIDs removes the "images" edge to AlbumImage entities by IDs.
func (_u *AlbumUpdateOne) RemoveImageIDs(ids ...int) *AlbumUpdateOne {
	_u.mutation.RemoveImageIDs(ids...)
	return _u
}

// RemoveImages removes "images" edges to AlbumImage entities.
func (_u *AlbumUpdateOne) RemoveImages(v ...*AlbumImage) *AlbumUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveImageIDs(ids...)
}

// ClearListens clears all "listens" edges to the Listen entity.
func (_u *AlbumUpdateOne) ClearListens() *AlbumUpdateOne {
	_u.mutation.ClearListens()
	return _u
}

// RemoveListenIDs removes the "listens" edge to Listen entities by IDs.
func (_u *AlbumUpdateOne) RemoveListenIDs(ids ...int) *AlbumUpdateOne {
	_u.mutation.RemoveListenIDs(ids...)
	return _u
}

// RemoveListens removes "listens" edges to Listen entities.
func (_u *AlbumUpdateOne) RemoveListens(v ...*Listen) *AlbumUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveListenIDs(ids...)
}

// Where appends a list predicates to the AlbumUpdate builder.
func (_u *AlbumUpdateOne) Where(ps ...predicate.Album) *AlbumUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AlbumUpdateOne) Select(field string, fields ...string) *AlbumUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Album entity.
func (_u *AlbumUpdateOne) Save(ctx context.Context) (*Album, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AlbumUpdateOne) SaveX(ctx context.Context) *Album {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AlbumUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AlbumUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AlbumUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := album.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AlbumUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := album.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Album.name": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Album.user"`)
	}
	return nil
}

func (_u *AlbumUpdateOne) sqlSave(ctx context.Context) (_node *Album, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(album.Table, album.Columns, sqlgraph.NewFieldSpec(album.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Album.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, album.FieldID)
		for _, f := range fields {
			if !album.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != album.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(album.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortName(); ok {
		_spec.SetField(album.FieldSortName, field.TypeString, value)
	}
	if _u.mutation.SortNameCleared() {
		_spec.ClearField(album.FieldSortName, field.TypeString)
	}
	if value, ok := _u.mutation.MusicbrainzID(); ok {
		_spec.SetField(album.FieldMusicbrainzID, field.TypeString, value)
	}
	if _u.mutation.MusicbrainzIDCleared() {
		_spec.ClearField(album.FieldMusicbrainzID, field.TypeString)
	}
	if value, ok := _u.mutation.SpotifyID(); ok {
		_spec.SetField(album.FieldSpotifyID, field.TypeString, value)
	}
	if _u.mutation.SpotifyIDCleared() {
		_spec.ClearField(album.FieldSpotifyID, field.TypeString)
	}
	if value, ok := _u.mutation.ReleaseDate(); ok {
		_spec.SetField(album.FieldReleaseDate, field.TypeString, value)
	}
	if _u.mutation.ReleaseDateCleared() {
		_spec.ClearField(album.FieldReleaseDate, field.TypeString)
	}
	if value, ok := _u.mutation.Year(); ok {
		_spec.SetField(album.FieldYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedYear(); ok {
		_spec.AddField(album.FieldYear, field.TypeInt, value)
	}
	if _u.mutation.YearCleared() {
		_spec.ClearField(album.FieldYear, field.TypeInt)
	}
	if value, ok := _u.mutation.Genre(); ok {
		_spec.SetField(album.FieldGenre, field.TypeString, value)
	}
	if _u.mutation.GenreCleared() {
		_spec.ClearField(album.FieldGenre, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(album.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, album.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(album.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.Popularity(); ok {
		_spec.SetField(album.FieldPopularity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPopularity(); ok {
		_spec.AddField(album.FieldPopularity, field.TypeInt, value)
	}
	if _u.mutation.PopularityCleared() {
		_spec.ClearField(album.FieldPopularity, field.TypeInt)
	}
	if value, ok := _u.mutation.TotalTracks(); ok {
		_spec.SetField(album.FieldTotalTracks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalTracks(); ok {
		_spec.AddField(album.FieldTotalTracks, field.TypeInt, value)
	}
	if _u.mutation.TotalTracksCleared() {
		_spec.ClearField(album.FieldTotalTracks, field.TypeInt)
	}
	if value, ok := _u.mutation.AlbumType(); ok {
		_spec.SetField(album.FieldAlbumType, field.TypeString, value)
	}
	if _u.mutation.AlbumTypeCleared() {
		_spec.ClearField(album.FieldAlbumType, field.TypeString)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(album.FieldLabel, field.TypeString, value)
	}
	if _u.mutation.LabelCleared() {
		_spec.ClearField(album.FieldLabel, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(album.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastEnrichedAt(); ok {
		_spec.SetField(album.FieldLastEnrichedAt, field.TypeTime, value)
	}
	if _u.mutation.LastEnrichedAtCleared() {
		_spec.ClearField(album.FieldLastEnrichedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   album.UserTable,
			Columns: []string{album.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   album.UserTable,
			Columns: []string{album.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ArtistCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   album.ArtistTable,
			Columns: []string{album.ArtistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArtistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   album.ArtistTable,
			Columns: []string{album.ArtistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TracksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   album.TracksTable,
			Columns: []string{album.TracksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(track.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTracksIDs(); len(nodes) > 0 && !_u.mutation.TracksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   album.TracksTable,
			Columns: []string{album.TracksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(track.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TracksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   album.TracksTable,
			Columns: []string{album.TracksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(track.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ImagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   album.ImagesTable,
			Columns: []string{album.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(albumimage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedImagesIDs(); len(nodes) > 0 && !_u.mutation.ImagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   album.ImagesTable,
			Columns: []string{album.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(albumimage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ImagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   album.ImagesTable,
			Columns: []string{album.ImagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(albumimage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ListensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   album.ListensTable,
			Columns: []string{album.ListensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listen.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedListensIDs(); len(nodes) > 0 && !_u.mutation.ListensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   album.ListensTable,
			Columns: []string{album.ListensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listen.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ListensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   album.ListensTable,
			Columns: []string{album.ListensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listen.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Album{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{album.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
