// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"spotter/ent/artistimage"
	"spotter/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ArtistImageDelete is the builder for deleting a ArtistImage entity.
type ArtistImageDelete struct {
	config
	hooks    []Hook
	mutation *ArtistImageMutation
}

// Where appends a list predicates to the ArtistImageDelete builder.
func (_d *ArtistImageDelete) Where(ps ...predicate.ArtistImage) *ArtistImageDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ArtistImageDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ArtistImageDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ArtistImageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(artistimage.Table, sqlgraph.NewFieldSpec(artistimage.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ArtistImageDeleteOne is the builder for deleting a single ArtistImage entity.
type ArtistImageDeleteOne struct {
	_d *ArtistImageDelete
}

// Where appends a list predicates to the ArtistImageDelete builder.
func (_d *ArtistImageDeleteOne) Where(ps ...predicate.ArtistImage) *ArtistImageDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ArtistImageDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{artistimage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ArtistImageDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
