// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"spotter/ent/artist"
	"spotter/ent/artistimage"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ArtistImage is the model entity for the ArtistImage schema.
type ArtistImage struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Type of artist image
	ImageType artistimage.ImageType `json:"image_type,omitempty"`
	// Provider that supplied this image (fanart, spotify, lastfm, etc.)
	Source string `json:"source,omitempty"`
	// Original URL of the image
	URL string `json:"url,omitempty"`
	// Local file path if image has been downloaded
	LocalPath string `json:"local_path,omitempty"`
	// Image width in pixels
	Width *int `json:"width,omitempty"`
	// Image height in pixels
	Height *int `json:"height,omitempty"`
	// Like count from Fanart.tv for sorting by popularity
	Likes *int `json:"likes,omitempty"`
	// Whether this is the primary image of its type
	IsPrimary bool `json:"is_primary,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ArtistImageQuery when eager-loading is set.
	Edges         ArtistImageEdges `json:"edges"`
	artist_images *int
	selectValues  sql.SelectValues
}

// ArtistImageEdges holds the relations/edges for other nodes in the graph.
type ArtistImageEdges struct {
	// Artist holds the value of the artist edge.
	Artist *Artist `json:"artist,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ArtistOrErr returns the Artist value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ArtistImageEdges) ArtistOrErr() (*Artist, error) {
	if e.Artist != nil {
		return e.Artist, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: artist.Label}
	}
	return nil, &NotLoadedError{edge: "artist"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ArtistImage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case artistimage.FieldIsPrimary:
			values[i] = new(sql.NullBool)
		case artistimage.FieldID, artistimage.FieldWidth, artistimage.FieldHeight, artistimage.FieldLikes:
			values[i] = new(sql.NullInt64)
		case artistimage.FieldImageType, artistimage.FieldSource, artistimage.FieldURL, artistimage.FieldLocalPath:
			values[i] = new(sql.NullString)
		case artistimage.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case artistimage.ForeignKeys[0]: // artist_images
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ArtistImage fields.
func (_m *ArtistImage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case artistimage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case artistimage.FieldImageType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_type", values[i])
			} else if value.Valid {
				_m.ImageType = artistimage.ImageType(value.String)
			}
		case artistimage.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case artistimage.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case artistimage.FieldLocalPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field local_path", values[i])
			} else if value.Valid {
				_m.LocalPath = value.String
			}
		case artistimage.FieldWidth:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field width", values[i])
			} else if value.Valid {
				_m.Width = new(int)
				*_m.Width = int(value.Int64)
			}
		case artistimage.FieldHeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field height", values[i])
			} else if value.Valid {
				_m.Height = new(int)
				*_m.Height = int(value.Int64)
			}
		case artistimage.FieldLikes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field likes", values[i])
			} else if value.Valid {
				_m.Likes = new(int)
				*_m.Likes = int(value.Int64)
			}
		case artistimage.FieldIsPrimary:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_primary", values[i])
			} else if value.Valid {
				_m.IsPrimary = value.Bool
			}
		case artistimage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case artistimage.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field artist_images", value)
			} else if value.Valid {
				_m.artist_images = new(int)
				*_m.artist_images = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ArtistImage.
// This includes values selected through modifiers, order, etc.
func (_m *ArtistImage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryArtist queries the "artist" edge of the ArtistImage entity.
func (_m *ArtistImage) QueryArtist() *ArtistQuery {
	return NewArtistImageClient(_m.config).QueryArtist(_m)
}

// Update returns a builder for updating this ArtistImage.
// Note that you need to call ArtistImage.Unwrap() before calling this method if this ArtistImage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ArtistImage) Update() *ArtistImageUpdateOne {
	return NewArtistImageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ArtistImage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ArtistImage) Unwrap() *ArtistImage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ArtistImage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ArtistImage) String() string {
	var builder strings.Builder
	builder.WriteString("ArtistImage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("image_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.ImageType))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	builder.WriteString("local_path=")
	builder.WriteString(_m.LocalPath)
	builder.WriteString(", ")
	if v := _m.Width; v != nil {
		builder.WriteString("width=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Height; v != nil {
		builder.WriteString("height=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Likes; v != nil {
		builder.WriteString("likes=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("is_primary=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsPrimary))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ArtistImages is a parsable slice of ArtistImage.
type ArtistImages []*ArtistImage
