// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"spotter/ent/album"
	"spotter/ent/artist"
	"spotter/ent/listen"
	"spotter/ent/track"
	"spotter/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Listen is the model entity for the Listen schema.
type Listen struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TrackName holds the value of the "track_name" field.
	TrackName string `json:"track_name,omitempty"`
	// ArtistName holds the value of the "artist_name" field.
	ArtistName string `json:"artist_name,omitempty"`
	// AlbumName holds the value of the "album_name" field.
	AlbumName string `json:"album_name,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// PlayedAt holds the value of the "played_at" field.
	PlayedAt time.Time `json:"played_at,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ListenQuery when eager-loading is set.
	Edges          ListenEdges `json:"edges"`
	album_listens  *int
	artist_listens *int
	track_listens  *int
	user_listens   *int
	selectValues   sql.SelectValues
}

// ListenEdges holds the relations/edges for other nodes in the graph.
type ListenEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Artist holds the value of the artist edge.
	Artist *Artist `json:"artist,omitempty"`
	// Album holds the value of the album edge.
	Album *Album `json:"album,omitempty"`
	// Track holds the value of the track edge.
	Track *Track `json:"track,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ListenEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ArtistOrErr returns the Artist value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ListenEdges) ArtistOrErr() (*Artist, error) {
	if e.Artist != nil {
		return e.Artist, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: artist.Label}
	}
	return nil, &NotLoadedError{edge: "artist"}
}

// AlbumOrErr returns the Album value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ListenEdges) AlbumOrErr() (*Album, error) {
	if e.Album != nil {
		return e.Album, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: album.Label}
	}
	return nil, &NotLoadedError{edge: "album"}
}

// TrackOrErr returns the Track value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ListenEdges) TrackOrErr() (*Track, error) {
	if e.Track != nil {
		return e.Track, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: track.Label}
	}
	return nil, &NotLoadedError{edge: "track"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Listen) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case listen.FieldID:
			values[i] = new(sql.NullInt64)
		case listen.FieldTrackName, listen.FieldArtistName, listen.FieldAlbumName, listen.FieldSource, listen.FieldURL:
			values[i] = new(sql.NullString)
		case listen.FieldPlayedAt:
			values[i] = new(sql.NullTime)
		case listen.ForeignKeys[0]: // album_listens
			values[i] = new(sql.NullInt64)
		case listen.ForeignKeys[1]: // artist_listens
			values[i] = new(sql.NullInt64)
		case listen.ForeignKeys[2]: // track_listens
			values[i] = new(sql.NullInt64)
		case listen.ForeignKeys[3]: // user_listens
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Listen fields.
func (_m *Listen) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case listen.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case listen.FieldTrackName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field track_name", values[i])
			} else if value.Valid {
				_m.TrackName = value.String
			}
		case listen.FieldArtistName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field artist_name", values[i])
			} else if value.Valid {
				_m.ArtistName = value.String
			}
		case listen.FieldAlbumName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field album_name", values[i])
			} else if value.Valid {
				_m.AlbumName = value.String
			}
		case listen.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case listen.FieldPlayedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field played_at", values[i])
			} else if value.Valid {
				_m.PlayedAt = value.Time
			}
		case listen.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case listen.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field album_listens", value)
			} else if value.Valid {
				_m.album_listens = new(int)
				*_m.album_listens = int(value.Int64)
			}
		case listen.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field artist_listens", value)
			} else if value.Valid {
				_m.artist_listens = new(int)
				*_m.artist_listens = int(value.Int64)
			}
		case listen.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field track_listens", value)
			} else if value.Valid {
				_m.track_listens = new(int)
				*_m.track_listens = int(value.Int64)
			}
		case listen.ForeignKeys[3]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_listens", value)
			} else if value.Valid {
				_m.user_listens = new(int)
				*_m.user_listens = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Listen.
// This includes values selected through modifiers, order, etc.
func (_m *Listen) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Listen entity.
func (_m *Listen) QueryUser() *UserQuery {
	return NewListenClient(_m.config).QueryUser(_m)
}

// QueryArtist queries the "artist" edge of the Listen entity.
func (_m *Listen) QueryArtist() *ArtistQuery {
	return NewListenClient(_m.config).QueryArtist(_m)
}

// QueryAlbum queries the "album" edge of the Listen entity.
func (_m *Listen) QueryAlbum() *AlbumQuery {
	return NewListenClient(_m.config).QueryAlbum(_m)
}

// QueryTrack queries the "track" edge of the Listen entity.
func (_m *Listen) QueryTrack() *TrackQuery {
	return NewListenClient(_m.config).QueryTrack(_m)
}

// Update returns a builder for updating this Listen.
// Note that you need to call Listen.Unwrap() before calling this method if this Listen
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Listen) Update() *ListenUpdateOne {
	return NewListenClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Listen entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Listen) Unwrap() *Listen {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Listen is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Listen) String() string {
	var builder strings.Builder
	builder.WriteString("Listen(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("track_name=")
	builder.WriteString(_m.TrackName)
	builder.WriteString(", ")
	builder.WriteString("artist_name=")
	builder.WriteString(_m.ArtistName)
	builder.WriteString(", ")
	builder.WriteString("album_name=")
	builder.WriteString(_m.AlbumName)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("played_at=")
	builder.WriteString(_m.PlayedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteByte(')')
	return builder.String()
}

// Listens is a parsable slice of Listen.
type Listens []*Listen
