// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"spotter/ent/album"
	"spotter/ent/artist"
	"spotter/ent/listen"
	"spotter/ent/predicate"
	"spotter/ent/track"
	"spotter/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ListenUpdate is the builder for updating Listen entities.
type ListenUpdate struct {
	config
	hooks    []Hook
	mutation *ListenMutation
}

// Where appends a list predicates to the ListenUpdate builder.
func (_u *ListenUpdate) Where(ps ...predicate.Listen) *ListenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTrackName sets the "track_name" field.
func (_u *ListenUpdate) SetTrackName(v string) *ListenUpdate {
	_u.mutation.SetTrackName(v)
	return _u
}

// SetNillableTrackName sets the "track_name" field if the given value is not nil.
func (_u *ListenUpdate) SetNillableTrackName(v *string) *ListenUpdate {
	if v != nil {
		_u.SetTrackName(*v)
	}
	return _u
}

// SetArtistName sets the "artist_name" field.
func (_u *ListenUpdate) SetArtistName(v string) *ListenUpdate {
	_u.mutation.SetArtistName(v)
	return _u
}

// SetNillableArtistName sets the "artist_name" field if the given value is not nil.
func (_u *ListenUpdate) SetNillableArtistName(v *string) *ListenUpdate {
	if v != nil {
		_u.SetArtistName(*v)
	}
	return _u
}

// SetAlbumName sets the "album_name" field.
func (_u *ListenUpdate) SetAlbumName(v string) *ListenUpdate {
	_u.mutation.SetAlbumName(v)
	return _u
}

// SetNillableAlbumName sets the "album_name" field if the given value is not nil.
func (_u *ListenUpdate) SetNillableAlbumName(v *string) *ListenUpdate {
	if v != nil {
		_u.SetAlbumName(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *ListenUpdate) SetSource(v string) *ListenUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *ListenUpdate) SetNillableSource(v *string) *ListenUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetPlayedAt sets the "played_at" field.
func (_u *ListenUpdate) SetPlayedAt(v time.Time) *ListenUpdate {
	_u.mutation.SetPlayedAt(v)
	return _u
}

// SetNillablePlayedAt sets the "played_at" field if the given value is not nil.
func (_u *ListenUpdate) SetNillablePlayedAt(v *time.Time) *ListenUpdate {
	if v != nil {
		_u.SetPlayedAt(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *ListenUpdate) SetURL(v string) *ListenUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *ListenUpdate) SetNillableURL(v *string) *ListenUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *ListenUpdate) ClearURL() *ListenUpdate {
	_u.mutation.ClearURL()
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *ListenUpdate) SetUserID(id int) *ListenUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ListenUpdate) SetUser(v *User) *ListenUpdate {
	return _u.SetUserID(v.ID)
}

// SetArtistID sets the "artist" edge to the Artist entity by ID.
func (_u *ListenUpdate) SetArtistID(id int) *ListenUpdate {
	_u.mutation.SetArtistID(id)
	return _u
}

// SetNillableArtistID sets the "artist" edge to the Artist entity by ID if the given value is not nil.
func (_u *ListenUpdate) SetNillableArtistID(id *int) *ListenUpdate {
	if id != nil {
		_u = _u.SetArtistID(*id)
	}
	return _u
}

// SetArtist sets the "artist" edge to the Artist entity.
func (_u *ListenUpdate) SetArtist(v *Artist) *ListenUpdate {
	return _u.SetArtistID(v.ID)
}

// SetAlbumID sets the "album" edge to the Album entity by ID.
func (_u *ListenUpdate) SetAlbumID(id int) *ListenUpdate {
	_u.mutation.SetAlbumID(id)
	return _u
}

// SetNillableAlbumID sets the "album" edge to the Album entity by ID if the given value is not nil.
func (_u *ListenUpdate) SetNillableAlbumID(id *int) *ListenUpdate {
	if id != nil {
		_u = _u.SetAlbumID(*id)
	}
	return _u
}

// SetAlbum sets the "album" edge to the Album entity.
func (_u *ListenUpdate) SetAlbum(v *Album) *ListenUpdate {
	return _u.SetAlbumID(v.ID)
}

// SetTrackID sets the "track" edge to the Track entity by ID.
func (_u *ListenUpdate) SetTrackID(id int) *ListenUpdate {
	_u.mutation.SetTrackID(id)
	return _u
}

// SetNillableTrackID sets the "track" edge to the Track entity by ID if the given value is not nil.
func (_u *ListenUpdate) SetNillableTrackID(id *int) *ListenUpdate {
	if id != nil {
		_u = _u.SetTrackID(*id)
	}
	return _u
}

// SetTrack sets the "track" edge to the Track entity.
func (_u *ListenUpdate) SetTrack(v *Track) *ListenUpdate {
	return _u.SetTrackID(v.ID)
}

// Mutation returns the ListenMutation object of the builder.
func (_u *ListenUpdate) Mutation() *ListenMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ListenUpdate) ClearUser() *ListenUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearArtist clears the "artist" edge to the Artist entity.
func (_u *ListenUpdate) ClearArtist() *ListenUpdate {
	_u.mutation.ClearArtist()
	return _u
}

// ClearAlbum clears the "album" edge to the Album entity.
func (_u *ListenUpdate) ClearAlbum() *ListenUpdate {
	_u.mutation.ClearAlbum()
	return _u
}

// ClearTrack clears the "track" edge to the Track entity.
func (_u *ListenUpdate) ClearTrack() *ListenUpdate {
	_u.mutation.ClearTrack()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ListenUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ListenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ListenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ListenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ListenUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Listen.user"`)
	}
	return nil
}

func (_u *ListenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(listen.Table, listen.Columns, sqlgraph.NewFieldSpec(listen.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TrackName(); ok {
		_spec.SetField(listen.FieldTrackName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ArtistName(); ok {
		_spec.SetField(listen.FieldArtistName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AlbumName(); ok {
		_spec.SetField(listen.FieldAlbumName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(listen.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlayedAt(); ok {
		_spec.SetField(listen.FieldPlayedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(listen.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(listen.FieldURL, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   listen.UserTable,
			Columns: []string{listen.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   listen.UserTable,
			Columns: []string{listen.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ArtistCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   listen.ArtistTable,
			Columns: []string{listen.ArtistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArtistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   listen.ArtistTable,
			Columns: []string{listen.ArtistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AlbumCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   listen.AlbumTable,
			Columns: []string{listen.AlbumColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(album.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AlbumIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   listen.AlbumTable,
			Columns: []string{listen.AlbumColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(album.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TrackCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   listen.TrackTable,
			Columns: []string{listen.TrackColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(track.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TrackIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   listen.TrackTable,
			Columns: []string{listen.TrackColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(track.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{listen.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ListenUpdateOne is the builder for updating a single Listen entity.
type ListenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ListenMutation
}

// SetTrackName sets the "track_name" field.
func (_u *ListenUpdateOne) SetTrackName(v string) *ListenUpdateOne {
	_u.mutation.SetTrackName(v)
	return _u
}

// SetNillableTrackName sets the "track_name" field if the given value is not nil.
func (_u *ListenUpdateOne) SetNillableTrackName(v *string) *ListenUpdateOne {
	if v != nil {
		_u.SetTrackName(*v)
	}
	return _u
}

// SetArtistName sets the "artist_name" field.
func (_u *ListenUpdateOne) SetArtistName(v string) *ListenUpdateOne {
	_u.mutation.SetArtistName(v)
	return _u
}

// SetNillableArtistName sets the "artist_name" field if the given value is not nil.
func (_u *ListenUpdateOne) SetNillableArtistName(v *string) *ListenUpdateOne {
	if v != nil {
		_u.SetArtistName(*v)
	}
	return _u
}

// SetAlbumName sets the "album_name" field.
func (_u *ListenUpdateOne) SetAlbumName(v string) *ListenUpdateOne {
	_u.mutation.SetAlbumName(v)
	return _u
}

// SetNillableAlbumName sets the "album_name" field if the given value is not nil.
func (_u *ListenUpdateOne) SetNillableAlbumName(v *string) *ListenUpdateOne {
	if v != nil {
		_u.SetAlbumName(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *ListenUpdateOne) SetSource(v string) *ListenUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *ListenUpdateOne) SetNillableSource(v *string) *ListenUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetPlayedAt sets the "played_at" field.
func (_u *ListenUpdateOne) SetPlayedAt(v time.Time) *ListenUpdateOne {
	_u.mutation.SetPlayedAt(v)
	return _u
}

// SetNillablePlayedAt sets the "played_at" field if the given value is not nil.
func (_u *ListenUpdateOne) SetNillablePlayedAt(v *time.Time) *ListenUpdateOne {
	if v != nil {
		_u.SetPlayedAt(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *ListenUpdateOne) SetURL(v string) *ListenUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *ListenUpdateOne) SetNillableURL(v *string) *ListenUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *ListenUpdateOne) ClearURL() *ListenUpdateOne {
	_u.mutation.ClearURL()
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *ListenUpdateOne) SetUserID(id int) *ListenUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ListenUpdateOne) SetUser(v *User) *ListenUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetArtistID sets the "artist" edge to the Artist entity by ID.
func (_u *ListenUpdateOne) SetArtistID(id int) *ListenUpdateOne {
	_u.mutation.SetArtistID(id)
	return _u
}

// SetNillableArtistID sets the "artist" edge to the Artist entity by ID if the given value is not nil.
func (_u *ListenUpdateOne) SetNillableArtistID(id *int) *ListenUpdateOne {
	if id != nil {
		_u = _u.SetArtistID(*id)
	}
	return _u
}

// SetArtist sets the "artist" edge to the Artist entity.
func (_u *ListenUpdateOne) SetArtist(v *Artist) *ListenUpdateOne {
	return _u.SetArtistID(v.ID)
}

// SetAlbumID sets the "album" edge to the Album entity by ID.
func (_u *ListenUpdateOne) SetAlbumID(id int) *ListenUpdateOne {
	_u.mutation.SetAlbumID(id)
	return _u
}

// SetNillableAlbumID sets the "album" edge to the Album entity by ID if the given value is not nil.
func (_u *ListenUpdateOne) SetNillableAlbumID(id *int) *ListenUpdateOne {
	if id != nil {
		_u = _u.SetAlbumID(*id)
	}
	return _u
}

// SetAlbum sets the "album" edge to the Album entity.
func (_u *ListenUpdateOne) SetAlbum(v *Album) *ListenUpdateOne {
	return _u.SetAlbumID(v.ID)
}

// SetTrackID sets the "track" edge to the Track entity by ID.
func (_u *ListenUpdateOne) SetTrackID(id int) *ListenUpdateOne {
	_u.mutation.SetTrackID(id)
	return _u
}

// SetNillableTrackID sets the "track" edge to the Track entity by ID if the given value is not nil.
func (_u *ListenUpdateOne) SetNillableTrackID(id *int) *ListenUpdateOne {
	if id != nil {
		_u = _u.SetTrackID(*id)
	}
	return _u
}

// SetTrack sets the "track" edge to the Track entity.
func (_u *ListenUpdateOne) SetTrack(v *Track) *ListenUpdateOne {
	return _u.SetTrackID(v.ID)
}

// Mutation returns the ListenMutation object of the builder.
func (_u *ListenUpdateOne) Mutation() *ListenMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ListenUpdateOne) ClearUser() *ListenUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearArtist clears the "artist" edge to the Artist entity.
func (_u *ListenUpdateOne) ClearArtist() *ListenUpdateOne {
	_u.mutation.ClearArtist()
	return _u
}

// ClearAlbum clears the "album" edge to the Album entity.
func (_u *ListenUpdateOne) ClearAlbum() *ListenUpdateOne {
	_u.mutation.ClearAlbum()
	return _u
}

// ClearTrack clears the "track" edge to the Track entity.
func (_u *ListenUpdateOne) ClearTrack() *ListenUpdateOne {
	_u.mutation.ClearTrack()
	return _u
}

// Where appends a list predicates to the ListenUpdate builder.
func (_u *ListenUpdateOne) Where(ps ...predicate.Listen) *ListenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ListenUpdateOne) Select(field string, fields ...string) *ListenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Listen entity.
func (_u *ListenUpdateOne) Save(ctx context.Context) (*Listen, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ListenUpdateOne) SaveX(ctx context.Context) *Listen {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ListenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ListenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ListenUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Listen.user"`)
	}
	return nil
}

func (_u *ListenUpdateOne) sqlSave(ctx context.Context) (_node *Listen, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(listen.Table, listen.Columns, sqlgraph.NewFieldSpec(listen.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Listen.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, listen.FieldID)
		for _, f := range fields {
			if !listen.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != listen.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TrackName(); ok {
		_spec.SetField(listen.FieldTrackName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ArtistName(); ok {
		_spec.SetField(listen.FieldArtistName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AlbumName(); ok {
		_spec.SetField(listen.FieldAlbumName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(listen.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlayedAt(); ok {
		_spec.SetField(listen.FieldPlayedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(listen.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(listen.FieldURL, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   listen.UserTable,
			Columns: []string{listen.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   listen.UserTable,
			Columns: []string{listen.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ArtistCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   listen.ArtistTable,
			Columns: []string{listen.ArtistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArtistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   listen.ArtistTable,
			Columns: []string{listen.ArtistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AlbumCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   listen.AlbumTable,
			Columns: []string{listen.AlbumColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(album.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AlbumIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   listen.AlbumTable,
			Columns: []string{listen.AlbumColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(album.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TrackCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   listen.TrackTable,
			Columns: []string{listen.TrackColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(track.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TrackIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   listen.TrackTable,
			Columns: []string{listen.TrackColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(track.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Listen{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{listen.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
