// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"spotter/ent/navidromeauth"
	"spotter/ent/user"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NavidromeAuthCreate is the builder for creating a NavidromeAuth entity.
type NavidromeAuthCreate struct {
	config
	mutation *NavidromeAuthMutation
	hooks    []Hook
}

// SetPassword sets the "password" field.
func (_c *NavidromeAuthCreate) SetPassword(v string) *NavidromeAuthCreate {
	_c.mutation.SetPassword(v)
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *NavidromeAuthCreate) SetUserID(id int) *NavidromeAuthCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *NavidromeAuthCreate) SetUser(v *User) *NavidromeAuthCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the NavidromeAuthMutation object of the builder.
func (_c *NavidromeAuthCreate) Mutation() *NavidromeAuthMutation {
	return _c.mutation
}

// Save creates the NavidromeAuth in the database.
func (_c *NavidromeAuthCreate) Save(ctx context.Context) (*NavidromeAuth, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NavidromeAuthCreate) SaveX(ctx context.Context) *NavidromeAuth {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NavidromeAuthCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NavidromeAuthCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NavidromeAuthCreate) check() error {
	if _, ok := _c.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New(`ent: missing required field "NavidromeAuth.password"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "NavidromeAuth.user"`)}
	}
	return nil
}

func (_c *NavidromeAuthCreate) sqlSave(ctx context.Context) (*NavidromeAuth, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NavidromeAuthCreate) createSpec() (*NavidromeAuth, *sqlgraph.CreateSpec) {
	var (
		_node = &NavidromeAuth{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(navidromeauth.Table, sqlgraph.NewFieldSpec(navidromeauth.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Password(); ok {
		_spec.SetField(navidromeauth.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   navidromeauth.UserTable,
			Columns: []string{navidromeauth.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_navidrome_auth = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// NavidromeAuthCreateBulk is the builder for creating many NavidromeAuth entities in bulk.
type NavidromeAuthCreateBulk struct {
	config
	err      error
	builders []*NavidromeAuthCreate
}

// Save creates the NavidromeAuth entities in the database.
func (_c *NavidromeAuthCreateBulk) Save(ctx context.Context) ([]*NavidromeAuth, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NavidromeAuth, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NavidromeAuthMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NavidromeAuthCreateBulk) SaveX(ctx context.Context) []*NavidromeAuth {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NavidromeAuthCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NavidromeAuthCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
