// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"spotter/ent/predicate"
	"spotter/ent/spotifyauth"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SpotifyAuthDelete is the builder for deleting a SpotifyAuth entity.
type SpotifyAuthDelete struct {
	config
	hooks    []Hook
	mutation *SpotifyAuthMutation
}

// Where appends a list predicates to the SpotifyAuthDelete builder.
func (_d *SpotifyAuthDelete) Where(ps ...predicate.SpotifyAuth) *SpotifyAuthDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SpotifyAuthDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SpotifyAuthDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SpotifyAuthDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(spotifyauth.Table, sqlgraph.NewFieldSpec(spotifyauth.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SpotifyAuthDeleteOne is the builder for deleting a single SpotifyAuth entity.
type SpotifyAuthDeleteOne struct {
	_d *SpotifyAuthDelete
}

// Where appends a list predicates to the SpotifyAuthDelete builder.
func (_d *SpotifyAuthDeleteOne) Where(ps ...predicate.SpotifyAuth) *SpotifyAuthDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SpotifyAuthDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{spotifyauth.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SpotifyAuthDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
