// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"spotter/ent/syncevent"
	"spotter/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SyncEventCreate is the builder for creating a SyncEvent entity.
type SyncEventCreate struct {
	config
	mutation *SyncEventMutation
	hooks    []Hook
}

// SetEventType sets the "event_type" field.
func (_c *SyncEventCreate) SetEventType(v syncevent.EventType) *SyncEventCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *SyncEventCreate) SetProvider(v string) *SyncEventCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetMessage sets the "message" field.
func (_c *SyncEventCreate) SetMessage(v string) *SyncEventCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *SyncEventCreate) SetMetadata(v string) *SyncEventCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetNillableMetadata sets the "metadata" field if the given value is not nil.
func (_c *SyncEventCreate) SetNillableMetadata(v *string) *SyncEventCreate {
	if v != nil {
		_c.SetMetadata(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SyncEventCreate) SetCreatedAt(v time.Time) *SyncEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SyncEventCreate) SetNillableCreatedAt(v *time.Time) *SyncEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *SyncEventCreate) SetUserID(id int) *SyncEventCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *SyncEventCreate) SetUser(v *User) *SyncEventCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the SyncEventMutation object of the builder.
func (_c *SyncEventCreate) Mutation() *SyncEventMutation {
	return _c.mutation
}

// Save creates the SyncEvent in the database.
func (_c *SyncEventCreate) Save(ctx context.Context) (*SyncEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SyncEventCreate) SaveX(ctx context.Context) *SyncEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SyncEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SyncEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SyncEventCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := syncevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SyncEventCreate) check() error {
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "SyncEvent.event_type"`)}
	}
	if v, ok := _c.mutation.EventType(); ok {
		if err := syncevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "SyncEvent.event_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "SyncEvent.provider"`)}
	}
	if _, ok := _c.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required field "SyncEvent.message"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SyncEvent.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "SyncEvent.user"`)}
	}
	return nil
}

func (_c *SyncEventCreate) sqlSave(ctx context.Context) (*SyncEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SyncEventCreate) createSpec() (*SyncEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &SyncEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(syncevent.Table, sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(syncevent.FieldEventType, field.TypeEnum, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(syncevent.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(syncevent.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(syncevent.FieldMetadata, field.TypeString, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(syncevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   syncevent.UserTable,
			Columns: []string{syncevent.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_sync_events = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SyncEventCreateBulk is the builder for creating many SyncEvent entities in bulk.
type SyncEventCreateBulk struct {
	config
	err      error
	builders []*SyncEventCreate
}

// Save creates the SyncEvent entities in the database.
func (_c *SyncEventCreateBulk) Save(ctx context.Context) ([]*SyncEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SyncEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SyncEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SyncEventCreateBulk) SaveX(ctx context.Context) []*SyncEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SyncEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SyncEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
