// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"spotter/ent/predicate"
	"spotter/ent/syncevent"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SyncEventDelete is the builder for deleting a SyncEvent entity.
type SyncEventDelete struct {
	config
	hooks    []Hook
	mutation *SyncEventMutation
}

// Where appends a list predicates to the SyncEventDelete builder.
func (_d *SyncEventDelete) Where(ps ...predicate.SyncEvent) *SyncEventDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SyncEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SyncEventDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SyncEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(syncevent.Table, sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SyncEventDeleteOne is the builder for deleting a single SyncEvent entity.
type SyncEventDeleteOne struct {
	_d *SyncEventDelete
}

// Where appends a list predicates to the SyncEventDelete builder.
func (_d *SyncEventDeleteOne) Where(ps ...predicate.SyncEvent) *SyncEventDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SyncEventDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{syncevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SyncEventDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
