// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"spotter/ent/album"
	"spotter/ent/artist"
	"spotter/ent/lastfmauth"
	"spotter/ent/listen"
	"spotter/ent/navidromeauth"
	"spotter/ent/playlist"
	"spotter/ent/predicate"
	"spotter/ent/spotifyauth"
	"spotter/ent/syncevent"
	"spotter/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUsername sets the "username" field.
func (_u *UserUpdate) SetUsername(v string) *UserUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserUpdate) SetNillableUsername(v *string) *UserUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *UserUpdate) ClearEmail() *UserUpdate {
	_u.mutation.ClearEmail()
	return _u
}

// SetTheme sets the "theme" field.
func (_u *UserUpdate) SetTheme(v string) *UserUpdate {
	_u.mutation.SetTheme(v)
	return _u
}

// SetNillableTheme sets the "theme" field if the given value is not nil.
func (_u *UserUpdate) SetNillableTheme(v *string) *UserUpdate {
	if v != nil {
		_u.SetTheme(*v)
	}
	return _u
}

// SetSystemPrompt sets the "system_prompt" field.
func (_u *UserUpdate) SetSystemPrompt(v string) *UserUpdate {
	_u.mutation.SetSystemPrompt(v)
	return _u
}

// SetNillableSystemPrompt sets the "system_prompt" field if the given value is not nil.
func (_u *UserUpdate) SetNillableSystemPrompt(v *string) *UserUpdate {
	if v != nil {
		_u.SetSystemPrompt(*v)
	}
	return _u
}

// ClearSystemPrompt clears the value of the "system_prompt" field.
func (_u *UserUpdate) ClearSystemPrompt() *UserUpdate {
	_u.mutation.ClearSystemPrompt()
	return _u
}

// SetPaginationSize sets the "pagination_size" field.
func (_u *UserUpdate) SetPaginationSize(v int) *UserUpdate {
	_u.mutation.ResetPaginationSize()
	_u.mutation.SetPaginationSize(v)
	return _u
}

// SetNillablePaginationSize sets the "pagination_size" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePaginationSize(v *int) *UserUpdate {
	if v != nil {
		_u.SetPaginationSize(*v)
	}
	return _u
}

// AddPaginationSize adds value to the "pagination_size" field.
func (_u *UserUpdate) AddPaginationSize(v int) *UserUpdate {
	_u.mutation.AddPaginationSize(v)
	return _u
}

// SetLastLoginAt sets the "last_login_at" field.
func (_u *UserUpdate) SetLastLoginAt(v time.Time) *UserUpdate {
	_u.mutation.SetLastLoginAt(v)
	return _u
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_u *UserUpdate) SetNillableLastLoginAt(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetLastLoginAt(*v)
	}
	return _u
}

// SetSpotifyAuthID sets the "spotify_auth" edge to the SpotifyAuth entity by ID.
func (_u *UserUpdate) SetSpotifyAuthID(id int) *UserUpdate {
	_u.mutation.SetSpotifyAuthID(id)
	return _u
}

// SetNillableSpotifyAuthID sets the "spotify_auth" edge to the SpotifyAuth entity by ID if the given value is not nil.
func (_u *UserUpdate) SetNillableSpotifyAuthID(id *int) *UserUpdate {
	if id != nil {
		_u = _u.SetSpotifyAuthID(*id)
	}
	return _u
}

// SetSpotifyAuth sets the "spotify_auth" edge to the SpotifyAuth entity.
func (_u *UserUpdate) SetSpotifyAuth(v *SpotifyAuth) *UserUpdate {
	return _u.SetSpotifyAuthID(v.ID)
}

// SetLastfmAuthID sets the "lastfm_auth" edge to the LastFMAuth entity by ID.
func (_u *UserUpdate) SetLastfmAuthID(id int) *UserUpdate {
	_u.mutation.SetLastfmAuthID(id)
	return _u
}

// SetNillableLastfmAuthID sets the "lastfm_auth" edge to the LastFMAuth entity by ID if the given value is not nil.
func (_u *UserUpdate) SetNillableLastfmAuthID(id *int) *UserUpdate {
	if id != nil {
		_u = _u.SetLastfmAuthID(*id)
	}
	return _u
}

// SetLastfmAuth sets the "lastfm_auth" edge to the LastFMAuth entity.
func (_u *UserUpdate) SetLastfmAuth(v *LastFMAuth) *UserUpdate {
	return _u.SetLastfmAuthID(v.ID)
}

// SetNavidromeAuthID sets the "navidrome_auth" edge to the NavidromeAuth entity by ID.
func (_u *UserUpdate) SetNavidromeAuthID(id int) *UserUpdate {
	_u.mutation.SetNavidromeAuthID(id)
	return _u
}

// SetNillableNavidromeAuthID sets the "navidrome_auth" edge to the NavidromeAuth entity by ID if the given value is not nil.
func (_u *UserUpdate) SetNillableNavidromeAuthID(id *int) *UserUpdate {
	if id != nil {
		_u = _u.SetNavidromeAuthID(*id)
	}
	return _u
}

// SetNavidromeAuth sets the "navidrome_auth" edge to the NavidromeAuth entity.
func (_u *UserUpdate) SetNavidromeAuth(v *NavidromeAuth) *UserUpdate {
	return _u.SetNavidromeAuthID(v.ID)
}

// AddPlaylistIDs adds the "playlists" edge to the Playlist entity by IDs.
func (_u *UserUpdate) AddPlaylistIDs(ids ...int) *UserUpdate {
	_u.mutation.AddPlaylistIDs(ids...)
	return _u
}

// AddPlaylists adds the "playlists" edges to the Playlist entity.
func (_u *UserUpdate) AddPlaylists(v ...*Playlist) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlaylistIDs(ids...)
}

// AddListenIDs adds the "listens" edge to the Listen entity by IDs.
func (_u *UserUpdate) AddListenIDs(ids ...int) *UserUpdate {
	_u.mutation.AddListenIDs(ids...)
	return _u
}

// AddListens adds the "listens" edges to the Listen entity.
func (_u *UserUpdate) AddListens(v ...*Listen) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddListenIDs(ids...)
}

// AddSyncEventIDs adds the "sync_events" edge to the SyncEvent entity by IDs.
func (_u *UserUpdate) AddSyncEventIDs(ids ...int) *UserUpdate {
	_u.mutation.AddSyncEventIDs(ids...)
	return _u
}

// AddSyncEvents adds the "sync_events" edges to the SyncEvent entity.
func (_u *UserUpdate) AddSyncEvents(v ...*SyncEvent) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSyncEventIDs(ids...)
}

// AddArtistIDs adds the "artists" edge to the Artist entity by IDs.
func (_u *UserUpdate) AddArtistIDs(ids ...int) *UserUpdate {
	_u.mutation.AddArtistIDs(ids...)
	return _u
}

// AddArtists adds the "artists" edges to the Artist entity.
func (_u *UserUpdate) AddArtists(v ...*Artist) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddArtistIDs(ids...)
}

// AddAlbumIDs adds the "albums" edge to the Album entity by IDs.
func (_u *UserUpdate) AddAlbumIDs(ids ...int) *UserUpdate {
	_u.mutation.AddAlbumIDs(ids...)
	return _u
}

// AddAlbums adds the "albums" edges to the Album entity.
func (_u *UserUpdate) AddAlbums(v ...*Album) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAlbumIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearSpotifyAuth clears the "spotify_auth" edge to the SpotifyAuth entity.
func (_u *UserUpdate) ClearSpotifyAuth() *UserUpdate {
	_u.mutation.ClearSpotifyAuth()
	return _u
}

// ClearLastfmAuth clears the "lastfm_auth" edge to the LastFMAuth entity.
func (_u *UserUpdate) ClearLastfmAuth() *UserUpdate {
	_u.mutation.ClearLastfmAuth()
	return _u
}

// ClearNavidromeAuth clears the "navidrome_auth" edge to the NavidromeAuth entity.
func (_u *UserUpdate) ClearNavidromeAuth() *UserUpdate {
	_u.mutation.ClearNavidromeAuth()
	return _u
}

// ClearPlaylists clears all "playlists" edges to the Playlist entity.
func (_u *UserUpdate) ClearPlaylists() *UserUpdate {
	_u.mutation.ClearPlaylists()
	return _u
}

// RemovePlaylistIDs removes the "playlists" edge to Playlist entities by IDs.
func (_u *UserUpdate) RemovePlaylistIDs(ids ...int) *UserUpdate {
	_u.mutation.RemovePlaylistIDs(ids...)
	return _u
}

// RemovePlaylists removes "playlists" edges to Playlist entities.
func (_u *UserUpdate) RemovePlaylists(v ...*Playlist) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlaylistIDs(ids...)
}

// ClearListens clears all "listens" edges to the Listen entity.
func (_u *UserUpdate) ClearListens() *UserUpdate {
	_u.mutation.ClearListens()
	return _u
}

// RemoveListenIDs removes the "listens" edge to Listen entities by IDs.
func (_u *UserUpdate) RemoveListenIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveListenIDs(ids...)
	return _u
}

// RemoveListens removes "listens" edges to Listen entities.
func (_u *UserUpdate) RemoveListens(v ...*Listen) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveListenIDs(ids...)
}

// ClearSyncEvents clears all "sync_events" edges to the SyncEvent entity.
func (_u *UserUpdate) ClearSyncEvents() *UserUpdate {
	_u.mutation.ClearSyncEvents()
	return _u
}

// RemoveSyncEventIDs removes the "sync_events" edge to SyncEvent entities by IDs.
func (_u *UserUpdate) RemoveSyncEventIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveSyncEventIDs(ids...)
	return _u
}

// RemoveSyncEvents removes "sync_events" edges to SyncEvent entities.
func (_u *UserUpdate) RemoveSyncEvents(v ...*SyncEvent) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSyncEventIDs(ids...)
}

// ClearArtists clears all "artists" edges to the Artist entity.
func (_u *UserUpdate) ClearArtists() *UserUpdate {
	_u.mutation.ClearArtists()
	return _u
}

// RemoveArtistIDs removes the "artists" edge to Artist entities by IDs.
func (_u *UserUpdate) RemoveArtistIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveArtistIDs(ids...)
	return _u
}

// RemoveArtists removes "artists" edges to Artist entities.
func (_u *UserUpdate) RemoveArtists(v ...*Artist) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveArtistIDs(ids...)
}

// ClearAlbums clears all "albums" edges to the Album entity.
func (_u *UserUpdate) ClearAlbums() *UserUpdate {
	_u.mutation.ClearAlbums()
	return _u
}

// RemoveAlbumIDs removes the "albums" edge to Album entities by IDs.
func (_u *UserUpdate) RemoveAlbumIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveAlbumIDs(ids...)
	return _u
}

// RemoveAlbums removes "albums" edges to Album entities.
func (_u *UserUpdate) RemoveAlbums(v ...*Album) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAlbumIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(user.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.Theme(); ok {
		_spec.SetField(user.FieldTheme, field.TypeString, value)
	}
	if value, ok := _u.mutation.SystemPrompt(); ok {
		_spec.SetField(user.FieldSystemPrompt, field.TypeString, value)
	}
	if _u.mutation.SystemPromptCleared() {
		_spec.ClearField(user.FieldSystemPrompt, field.TypeString)
	}
	if value, ok := _u.mutation.PaginationSize(); ok {
		_spec.SetField(user.FieldPaginationSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPaginationSize(); ok {
		_spec.AddField(user.FieldPaginationSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastLoginAt(); ok {
		_spec.SetField(user.FieldLastLoginAt, field.TypeTime, value)
	}
	if _u.mutation.SpotifyAuthCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.SpotifyAuthTable,
			Columns: []string{user.SpotifyAuthColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spotifyauth.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SpotifyAuthIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.SpotifyAuthTable,
			Columns: []string{user.SpotifyAuthColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spotifyauth.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LastfmAuthCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.LastfmAuthTable,
			Columns: []string{user.LastfmAuthColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lastfmauth.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LastfmAuthIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.LastfmAuthTable,
			Columns: []string{user.LastfmAuthColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lastfmauth.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NavidromeAuthCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.NavidromeAuthTable,
			Columns: []string{user.NavidromeAuthColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(navidromeauth.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NavidromeAuthIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.NavidromeAuthTable,
			Columns: []string{user.NavidromeAuthColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(navidromeauth.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlaylistsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PlaylistsTable,
			Columns: []string{user.PlaylistsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlaylistsIDs(); len(nodes) > 0 && !_u.mutation.PlaylistsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PlaylistsTable,
			Columns: []string{user.PlaylistsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlaylistsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PlaylistsTable,
			Columns: []string{user.PlaylistsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ListensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ListensTable,
			Columns: []string{user.ListensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listen.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedListensIDs(); len(nodes) > 0 && !_u.mutation.ListensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ListensTable,
			Columns: []string{user.ListensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listen.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ListensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ListensTable,
			Columns: []string{user.ListensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listen.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SyncEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SyncEventsTable,
			Columns: []string{user.SyncEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSyncEventsIDs(); len(nodes) > 0 && !_u.mutation.SyncEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SyncEventsTable,
			Columns: []string{user.SyncEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SyncEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SyncEventsTable,
			Columns: []string{user.SyncEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ArtistsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ArtistsTable,
			Columns: []string{user.ArtistsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedArtistsIDs(); len(nodes) > 0 && !_u.mutation.ArtistsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ArtistsTable,
			Columns: []string{user.ArtistsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArtistsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ArtistsTable,
			Columns: []string{user.ArtistsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AlbumsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AlbumsTable,
			Columns: []string{user.AlbumsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(album.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAlbumsIDs(); len(nodes) > 0 && !_u.mutation.AlbumsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AlbumsTable,
			Columns: []string{user.AlbumsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(album.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AlbumsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AlbumsTable,
			Columns: []string{user.AlbumsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(album.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetUsername sets the "username" field.
func (_u *UserUpdateOne) SetUsername(v string) *UserUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableUsername(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *UserUpdateOne) ClearEmail() *UserUpdateOne {
	_u.mutation.ClearEmail()
	return _u
}

// SetTheme sets the "theme" field.
func (_u *UserUpdateOne) SetTheme(v string) *UserUpdateOne {
	_u.mutation.SetTheme(v)
	return _u
}

// SetNillableTheme sets the "theme" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableTheme(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetTheme(*v)
	}
	return _u
}

// SetSystemPrompt sets the "system_prompt" field.
func (_u *UserUpdateOne) SetSystemPrompt(v string) *UserUpdateOne {
	_u.mutation.SetSystemPrompt(v)
	return _u
}

// SetNillableSystemPrompt sets the "system_prompt" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableSystemPrompt(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetSystemPrompt(*v)
	}
	return _u
}

// ClearSystemPrompt clears the value of the "system_prompt" field.
func (_u *UserUpdateOne) ClearSystemPrompt() *UserUpdateOne {
	_u.mutation.ClearSystemPrompt()
	return _u
}

// SetPaginationSize sets the "pagination_size" field.
func (_u *UserUpdateOne) SetPaginationSize(v int) *UserUpdateOne {
	_u.mutation.ResetPaginationSize()
	_u.mutation.SetPaginationSize(v)
	return _u
}

// SetNillablePaginationSize sets the "pagination_size" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePaginationSize(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetPaginationSize(*v)
	}
	return _u
}

// AddPaginationSize adds value to the "pagination_size" field.
func (_u *UserUpdateOne) AddPaginationSize(v int) *UserUpdateOne {
	_u.mutation.AddPaginationSize(v)
	return _u
}

// SetLastLoginAt sets the "last_login_at" field.
func (_u *UserUpdateOne) SetLastLoginAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetLastLoginAt(v)
	return _u
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableLastLoginAt(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetLastLoginAt(*v)
	}
	return _u
}

// SetSpotifyAuthID sets the "spotify_auth" edge to the SpotifyAuth entity by ID.
func (_u *UserUpdateOne) SetSpotifyAuthID(id int) *UserUpdateOne {
	_u.mutation.SetSpotifyAuthID(id)
	return _u
}

// SetNillableSpotifyAuthID sets the "spotify_auth" edge to the SpotifyAuth entity by ID if the given value is not nil.
func (_u *UserUpdateOne) SetNillableSpotifyAuthID(id *int) *UserUpdateOne {
	if id != nil {
		_u = _u.SetSpotifyAuthID(*id)
	}
	return _u
}

// SetSpotifyAuth sets the "spotify_auth" edge to the SpotifyAuth entity.
func (_u *UserUpdateOne) SetSpotifyAuth(v *SpotifyAuth) *UserUpdateOne {
	return _u.SetSpotifyAuthID(v.ID)
}

// SetLastfmAuthID sets the "lastfm_auth" edge to the LastFMAuth entity by ID.
func (_u *UserUpdateOne) SetLastfmAuthID(id int) *UserUpdateOne {
	_u.mutation.SetLastfmAuthID(id)
	return _u
}

// SetNillableLastfmAuthID sets the "lastfm_auth" edge to the LastFMAuth entity by ID if the given value is not nil.
func (_u *UserUpdateOne) SetNillableLastfmAuthID(id *int) *UserUpdateOne {
	if id != nil {
		_u = _u.SetLastfmAuthID(*id)
	}
	return _u
}

// SetLastfmAuth sets the "lastfm_auth" edge to the LastFMAuth entity.
func (_u *UserUpdateOne) SetLastfmAuth(v *LastFMAuth) *UserUpdateOne {
	return _u.SetLastfmAuthID(v.ID)
}

// SetNavidromeAuthID sets the "navidrome_auth" edge to the NavidromeAuth entity by ID.
func (_u *UserUpdateOne) SetNavidromeAuthID(id int) *UserUpdateOne {
	_u.mutation.SetNavidromeAuthID(id)
	return _u
}

// SetNillableNavidromeAuthID sets the "navidrome_auth" edge to the NavidromeAuth entity by ID if the given value is not nil.
func (_u *UserUpdateOne) SetNillableNavidromeAuthID(id *int) *UserUpdateOne {
	if id != nil {
		_u = _u.SetNavidromeAuthID(*id)
	}
	return _u
}

// SetNavidromeAuth sets the "navidrome_auth" edge to the NavidromeAuth entity.
func (_u *UserUpdateOne) SetNavidromeAuth(v *NavidromeAuth) *UserUpdateOne {
	return _u.SetNavidromeAuthID(v.ID)
}

// AddPlaylistIDs adds the "playlists" edge to the Playlist entity by IDs.
func (_u *UserUpdateOne) AddPlaylistIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddPlaylistIDs(ids...)
	return _u
}

// AddPlaylists adds the "playlists" edges to the Playlist entity.
func (_u *UserUpdateOne) AddPlaylists(v ...*Playlist) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlaylistIDs(ids...)
}

// AddListenIDs adds the "listens" edge to the Listen entity by IDs.
func (_u *UserUpdateOne) AddListenIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddListenIDs(ids...)
	return _u
}

// AddListens adds the "listens" edges to the Listen entity.
func (_u *UserUpdateOne) AddListens(v ...*Listen) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddListenIDs(ids...)
}

// AddSyncEventIDs adds the "sync_events" edge to the SyncEvent entity by IDs.
func (_u *UserUpdateOne) AddSyncEventIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddSyncEventIDs(ids...)
	return _u
}

// AddSyncEvents adds the "sync_events" edges to the SyncEvent entity.
func (_u *UserUpdateOne) AddSyncEvents(v ...*SyncEvent) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSyncEventIDs(ids...)
}

// AddArtistIDs adds the "artists" edge to the Artist entity by IDs.
func (_u *UserUpdateOne) AddArtistIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddArtistIDs(ids...)
	return _u
}

// AddArtists adds the "artists" edges to the Artist entity.
func (_u *UserUpdateOne) AddArtists(v ...*Artist) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddArtistIDs(ids...)
}

// AddAlbumIDs adds the "albums" edge to the Album entity by IDs.
func (_u *UserUpdateOne) AddAlbumIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddAlbumIDs(ids...)
	return _u
}

// AddAlbums adds the "albums" edges to the Album entity.
func (_u *UserUpdateOne) AddAlbums(v ...*Album) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAlbumIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearSpotifyAuth clears the "spotify_auth" edge to the SpotifyAuth entity.
func (_u *UserUpdateOne) ClearSpotifyAuth() *UserUpdateOne {
	_u.mutation.ClearSpotifyAuth()
	return _u
}

// ClearLastfmAuth clears the "lastfm_auth" edge to the LastFMAuth entity.
func (_u *UserUpdateOne) ClearLastfmAuth() *UserUpdateOne {
	_u.mutation.ClearLastfmAuth()
	return _u
}

// ClearNavidromeAuth clears the "navidrome_auth" edge to the NavidromeAuth entity.
func (_u *UserUpdateOne) ClearNavidromeAuth() *UserUpdateOne {
	_u.mutation.ClearNavidromeAuth()
	return _u
}

// ClearPlaylists clears all "playlists" edges to the Playlist entity.
func (_u *UserUpdateOne) ClearPlaylists() *UserUpdateOne {
	_u.mutation.ClearPlaylists()
	return _u
}

// RemovePlaylistIDs removes the "playlists" edge to Playlist entities by IDs.
func (_u *UserUpdateOne) RemovePlaylistIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemovePlaylistIDs(ids...)
	return _u
}

// RemovePlaylists removes "playlists" edges to Playlist entities.
func (_u *UserUpdateOne) RemovePlaylists(v ...*Playlist) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlaylistIDs(ids...)
}

// ClearListens clears all "listens" edges to the Listen entity.
func (_u *UserUpdateOne) ClearListens() *UserUpdateOne {
	_u.mutation.ClearListens()
	return _u
}

// RemoveListenIDs removes the "listens" edge to Listen entities by IDs.
func (_u *UserUpdateOne) RemoveListenIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveListenIDs(ids...)
	return _u
}

// RemoveListens removes "listens" edges to Listen entities.
func (_u *UserUpdateOne) RemoveListens(v ...*Listen) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveListenIDs(ids...)
}

// ClearSyncEvents clears all "sync_events" edges to the SyncEvent entity.
func (_u *UserUpdateOne) ClearSyncEvents() *UserUpdateOne {
	_u.mutation.ClearSyncEvents()
	return _u
}

// RemoveSyncEventIDs removes the "sync_events" edge to SyncEvent entities by IDs.
func (_u *UserUpdateOne) RemoveSyncEventIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveSyncEventIDs(ids...)
	return _u
}

// RemoveSyncEvents removes "sync_events" edges to SyncEvent entities.
func (_u *UserUpdateOne) RemoveSyncEvents(v ...*SyncEvent) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSyncEventIDs(ids...)
}

// ClearArtists clears all "artists" edges to the Artist entity.
func (_u *UserUpdateOne) ClearArtists() *UserUpdateOne {
	_u.mutation.ClearArtists()
	return _u
}

// RemoveArtistIDs removes the "artists" edge to Artist entities by IDs.
func (_u *UserUpdateOne) RemoveArtistIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveArtistIDs(ids...)
	return _u
}

// RemoveArtists removes "artists" edges to Artist entities.
func (_u *UserUpdateOne) RemoveArtists(v ...*Artist) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveArtistIDs(ids...)
}

// ClearAlbums clears all "albums" edges to the Album entity.
func (_u *UserUpdateOne) ClearAlbums() *UserUpdateOne {
	_u.mutation.ClearAlbums()
	return _u
}

// RemoveAlbumIDs removes the "albums" edge to Album entities by IDs.
func (_u *UserUpdateOne) RemoveAlbumIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveAlbumIDs(ids...)
	return _u
}

// RemoveAlbums removes "albums" edges to Album entities.
func (_u *UserUpdateOne) RemoveAlbums(v ...*Album) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAlbumIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(user.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.Theme(); ok {
		_spec.SetField(user.FieldTheme, field.TypeString, value)
	}
	if value, ok := _u.mutation.SystemPrompt(); ok {
		_spec.SetField(user.FieldSystemPrompt, field.TypeString, value)
	}
	if _u.mutation.SystemPromptCleared() {
		_spec.ClearField(user.FieldSystemPrompt, field.TypeString)
	}
	if value, ok := _u.mutation.PaginationSize(); ok {
		_spec.SetField(user.FieldPaginationSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPaginationSize(); ok {
		_spec.AddField(user.FieldPaginationSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastLoginAt(); ok {
		_spec.SetField(user.FieldLastLoginAt, field.TypeTime, value)
	}
	if _u.mutation.SpotifyAuthCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.SpotifyAuthTable,
			Columns: []string{user.SpotifyAuthColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spotifyauth.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SpotifyAuthIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.SpotifyAuthTable,
			Columns: []string{user.SpotifyAuthColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spotifyauth.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LastfmAuthCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.LastfmAuthTable,
			Columns: []string{user.LastfmAuthColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lastfmauth.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LastfmAuthIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.LastfmAuthTable,
			Columns: []string{user.LastfmAuthColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lastfmauth.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NavidromeAuthCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.NavidromeAuthTable,
			Columns: []string{user.NavidromeAuthColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(navidromeauth.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NavidromeAuthIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.NavidromeAuthTable,
			Columns: []string{user.NavidromeAuthColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(navidromeauth.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlaylistsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PlaylistsTable,
			Columns: []string{user.PlaylistsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlaylistsIDs(); len(nodes) > 0 && !_u.mutation.PlaylistsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PlaylistsTable,
			Columns: []string{user.PlaylistsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlaylistsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PlaylistsTable,
			Columns: []string{user.PlaylistsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playlist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ListensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ListensTable,
			Columns: []string{user.ListensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listen.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedListensIDs(); len(nodes) > 0 && !_u.mutation.ListensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ListensTable,
			Columns: []string{user.ListensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listen.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ListensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ListensTable,
			Columns: []string{user.ListensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listen.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SyncEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SyncEventsTable,
			Columns: []string{user.SyncEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSyncEventsIDs(); len(nodes) > 0 && !_u.mutation.SyncEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SyncEventsTable,
			Columns: []string{user.SyncEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SyncEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SyncEventsTable,
			Columns: []string{user.SyncEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syncevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ArtistsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ArtistsTable,
			Columns: []string{user.ArtistsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artist.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedArtistsIDs(); len(nodes) > 0 && !_u.mutation.ArtistsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ArtistsTable,
			Columns: []string{user.ArtistsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArtistsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ArtistsTable,
			Columns: []string{user.ArtistsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artist.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AlbumsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AlbumsTable,
			Columns: []string{user.AlbumsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(album.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAlbumsIDs(); len(nodes) > 0 && !_u.mutation.AlbumsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AlbumsTable,
			Columns: []string{user.AlbumsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(album.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AlbumsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AlbumsTable,
			Columns: []string{user.AlbumsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(album.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
