// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"spotter/ent/lastfmauth"
	"spotter/ent/listen"
	"spotter/ent/navidromeauth"
	"spotter/ent/predicate"
	"spotter/ent/spotifyauth"
	"spotter/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUsername sets the "username" field.
func (_u *UserUpdate) SetUsername(v string) *UserUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserUpdate) SetNillableUsername(v *string) *UserUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *UserUpdate) ClearEmail() *UserUpdate {
	_u.mutation.ClearEmail()
	return _u
}

// SetLastLoginAt sets the "last_login_at" field.
func (_u *UserUpdate) SetLastLoginAt(v time.Time) *UserUpdate {
	_u.mutation.SetLastLoginAt(v)
	return _u
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_u *UserUpdate) SetNillableLastLoginAt(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetLastLoginAt(*v)
	}
	return _u
}

// SetSpotifyAuthID sets the "spotify_auth" edge to the SpotifyAuth entity by ID.
func (_u *UserUpdate) SetSpotifyAuthID(id int) *UserUpdate {
	_u.mutation.SetSpotifyAuthID(id)
	return _u
}

// SetNillableSpotifyAuthID sets the "spotify_auth" edge to the SpotifyAuth entity by ID if the given value is not nil.
func (_u *UserUpdate) SetNillableSpotifyAuthID(id *int) *UserUpdate {
	if id != nil {
		_u = _u.SetSpotifyAuthID(*id)
	}
	return _u
}

// SetSpotifyAuth sets the "spotify_auth" edge to the SpotifyAuth entity.
func (_u *UserUpdate) SetSpotifyAuth(v *SpotifyAuth) *UserUpdate {
	return _u.SetSpotifyAuthID(v.ID)
}

// SetLastfmAuthID sets the "lastfm_auth" edge to the LastFMAuth entity by ID.
func (_u *UserUpdate) SetLastfmAuthID(id int) *UserUpdate {
	_u.mutation.SetLastfmAuthID(id)
	return _u
}

// SetNillableLastfmAuthID sets the "lastfm_auth" edge to the LastFMAuth entity by ID if the given value is not nil.
func (_u *UserUpdate) SetNillableLastfmAuthID(id *int) *UserUpdate {
	if id != nil {
		_u = _u.SetLastfmAuthID(*id)
	}
	return _u
}

// SetLastfmAuth sets the "lastfm_auth" edge to the LastFMAuth entity.
func (_u *UserUpdate) SetLastfmAuth(v *LastFMAuth) *UserUpdate {
	return _u.SetLastfmAuthID(v.ID)
}

// SetNavidromeAuthID sets the "navidrome_auth" edge to the NavidromeAuth entity by ID.
func (_u *UserUpdate) SetNavidromeAuthID(id int) *UserUpdate {
	_u.mutation.SetNavidromeAuthID(id)
	return _u
}

// SetNillableNavidromeAuthID sets the "navidrome_auth" edge to the NavidromeAuth entity by ID if the given value is not nil.
func (_u *UserUpdate) SetNillableNavidromeAuthID(id *int) *UserUpdate {
	if id != nil {
		_u = _u.SetNavidromeAuthID(*id)
	}
	return _u
}

// SetNavidromeAuth sets the "navidrome_auth" edge to the NavidromeAuth entity.
func (_u *UserUpdate) SetNavidromeAuth(v *NavidromeAuth) *UserUpdate {
	return _u.SetNavidromeAuthID(v.ID)
}

// AddListenIDs adds the "listens" edge to the Listen entity by IDs.
func (_u *UserUpdate) AddListenIDs(ids ...int) *UserUpdate {
	_u.mutation.AddListenIDs(ids...)
	return _u
}

// AddListens adds the "listens" edges to the Listen entity.
func (_u *UserUpdate) AddListens(v ...*Listen) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddListenIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearSpotifyAuth clears the "spotify_auth" edge to the SpotifyAuth entity.
func (_u *UserUpdate) ClearSpotifyAuth() *UserUpdate {
	_u.mutation.ClearSpotifyAuth()
	return _u
}

// ClearLastfmAuth clears the "lastfm_auth" edge to the LastFMAuth entity.
func (_u *UserUpdate) ClearLastfmAuth() *UserUpdate {
	_u.mutation.ClearLastfmAuth()
	return _u
}

// ClearNavidromeAuth clears the "navidrome_auth" edge to the NavidromeAuth entity.
func (_u *UserUpdate) ClearNavidromeAuth() *UserUpdate {
	_u.mutation.ClearNavidromeAuth()
	return _u
}

// ClearListens clears all "listens" edges to the Listen entity.
func (_u *UserUpdate) ClearListens() *UserUpdate {
	_u.mutation.ClearListens()
	return _u
}

// RemoveListenIDs removes the "listens" edge to Listen entities by IDs.
func (_u *UserUpdate) RemoveListenIDs(ids ...int) *UserUpdate {
	_u.mutation.RemoveListenIDs(ids...)
	return _u
}

// RemoveListens removes "listens" edges to Listen entities.
func (_u *UserUpdate) RemoveListens(v ...*Listen) *UserUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveListenIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(user.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.LastLoginAt(); ok {
		_spec.SetField(user.FieldLastLoginAt, field.TypeTime, value)
	}
	if _u.mutation.SpotifyAuthCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.SpotifyAuthTable,
			Columns: []string{user.SpotifyAuthColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spotifyauth.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SpotifyAuthIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.SpotifyAuthTable,
			Columns: []string{user.SpotifyAuthColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spotifyauth.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LastfmAuthCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.LastfmAuthTable,
			Columns: []string{user.LastfmAuthColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lastfmauth.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LastfmAuthIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.LastfmAuthTable,
			Columns: []string{user.LastfmAuthColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lastfmauth.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NavidromeAuthCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.NavidromeAuthTable,
			Columns: []string{user.NavidromeAuthColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(navidromeauth.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NavidromeAuthIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.NavidromeAuthTable,
			Columns: []string{user.NavidromeAuthColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(navidromeauth.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ListensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ListensTable,
			Columns: []string{user.ListensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listen.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedListensIDs(); len(nodes) > 0 && !_u.mutation.ListensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ListensTable,
			Columns: []string{user.ListensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listen.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ListensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ListensTable,
			Columns: []string{user.ListensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listen.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetUsername sets the "username" field.
func (_u *UserUpdateOne) SetUsername(v string) *UserUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableUsername(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *UserUpdateOne) ClearEmail() *UserUpdateOne {
	_u.mutation.ClearEmail()
	return _u
}

// SetLastLoginAt sets the "last_login_at" field.
func (_u *UserUpdateOne) SetLastLoginAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetLastLoginAt(v)
	return _u
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableLastLoginAt(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetLastLoginAt(*v)
	}
	return _u
}

// SetSpotifyAuthID sets the "spotify_auth" edge to the SpotifyAuth entity by ID.
func (_u *UserUpdateOne) SetSpotifyAuthID(id int) *UserUpdateOne {
	_u.mutation.SetSpotifyAuthID(id)
	return _u
}

// SetNillableSpotifyAuthID sets the "spotify_auth" edge to the SpotifyAuth entity by ID if the given value is not nil.
func (_u *UserUpdateOne) SetNillableSpotifyAuthID(id *int) *UserUpdateOne {
	if id != nil {
		_u = _u.SetSpotifyAuthID(*id)
	}
	return _u
}

// SetSpotifyAuth sets the "spotify_auth" edge to the SpotifyAuth entity.
func (_u *UserUpdateOne) SetSpotifyAuth(v *SpotifyAuth) *UserUpdateOne {
	return _u.SetSpotifyAuthID(v.ID)
}

// SetLastfmAuthID sets the "lastfm_auth" edge to the LastFMAuth entity by ID.
func (_u *UserUpdateOne) SetLastfmAuthID(id int) *UserUpdateOne {
	_u.mutation.SetLastfmAuthID(id)
	return _u
}

// SetNillableLastfmAuthID sets the "lastfm_auth" edge to the LastFMAuth entity by ID if the given value is not nil.
func (_u *UserUpdateOne) SetNillableLastfmAuthID(id *int) *UserUpdateOne {
	if id != nil {
		_u = _u.SetLastfmAuthID(*id)
	}
	return _u
}

// SetLastfmAuth sets the "lastfm_auth" edge to the LastFMAuth entity.
func (_u *UserUpdateOne) SetLastfmAuth(v *LastFMAuth) *UserUpdateOne {
	return _u.SetLastfmAuthID(v.ID)
}

// SetNavidromeAuthID sets the "navidrome_auth" edge to the NavidromeAuth entity by ID.
func (_u *UserUpdateOne) SetNavidromeAuthID(id int) *UserUpdateOne {
	_u.mutation.SetNavidromeAuthID(id)
	return _u
}

// SetNillableNavidromeAuthID sets the "navidrome_auth" edge to the NavidromeAuth entity by ID if the given value is not nil.
func (_u *UserUpdateOne) SetNillableNavidromeAuthID(id *int) *UserUpdateOne {
	if id != nil {
		_u = _u.SetNavidromeAuthID(*id)
	}
	return _u
}

// SetNavidromeAuth sets the "navidrome_auth" edge to the NavidromeAuth entity.
func (_u *UserUpdateOne) SetNavidromeAuth(v *NavidromeAuth) *UserUpdateOne {
	return _u.SetNavidromeAuthID(v.ID)
}

// AddListenIDs adds the "listens" edge to the Listen entity by IDs.
func (_u *UserUpdateOne) AddListenIDs(ids ...int) *UserUpdateOne {
	_u.mutation.AddListenIDs(ids...)
	return _u
}

// AddListens adds the "listens" edges to the Listen entity.
func (_u *UserUpdateOne) AddListens(v ...*Listen) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddListenIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearSpotifyAuth clears the "spotify_auth" edge to the SpotifyAuth entity.
func (_u *UserUpdateOne) ClearSpotifyAuth() *UserUpdateOne {
	_u.mutation.ClearSpotifyAuth()
	return _u
}

// ClearLastfmAuth clears the "lastfm_auth" edge to the LastFMAuth entity.
func (_u *UserUpdateOne) ClearLastfmAuth() *UserUpdateOne {
	_u.mutation.ClearLastfmAuth()
	return _u
}

// ClearNavidromeAuth clears the "navidrome_auth" edge to the NavidromeAuth entity.
func (_u *UserUpdateOne) ClearNavidromeAuth() *UserUpdateOne {
	_u.mutation.ClearNavidromeAuth()
	return _u
}

// ClearListens clears all "listens" edges to the Listen entity.
func (_u *UserUpdateOne) ClearListens() *UserUpdateOne {
	_u.mutation.ClearListens()
	return _u
}

// RemoveListenIDs removes the "listens" edge to Listen entities by IDs.
func (_u *UserUpdateOne) RemoveListenIDs(ids ...int) *UserUpdateOne {
	_u.mutation.RemoveListenIDs(ids...)
	return _u
}

// RemoveListens removes "listens" edges to Listen entities.
func (_u *UserUpdateOne) RemoveListens(v ...*Listen) *UserUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveListenIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(user.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.LastLoginAt(); ok {
		_spec.SetField(user.FieldLastLoginAt, field.TypeTime, value)
	}
	if _u.mutation.SpotifyAuthCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.SpotifyAuthTable,
			Columns: []string{user.SpotifyAuthColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spotifyauth.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SpotifyAuthIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.SpotifyAuthTable,
			Columns: []string{user.SpotifyAuthColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spotifyauth.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LastfmAuthCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.LastfmAuthTable,
			Columns: []string{user.LastfmAuthColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lastfmauth.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LastfmAuthIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.LastfmAuthTable,
			Columns: []string{user.LastfmAuthColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lastfmauth.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NavidromeAuthCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.NavidromeAuthTable,
			Columns: []string{user.NavidromeAuthColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(navidromeauth.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NavidromeAuthIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   user.NavidromeAuthTable,
			Columns: []string{user.NavidromeAuthColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(navidromeauth.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ListensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ListensTable,
			Columns: []string{user.ListensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listen.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedListensIDs(); len(nodes) > 0 && !_u.mutation.ListensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ListensTable,
			Columns: []string{user.ListensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listen.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ListensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ListensTable,
			Columns: []string{user.ListensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listen.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
