// Governing: ADR-0030 (LB Radio through the standard playlist pipeline),
// SPEC music-provider-integration REQ "ListenBrainz Provider" (REQ-PROV-053)
package listenbrainz

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"spotter/internal/providers"
)

// Radio modes accepted by the lb-radio endpoint. Easy generates data that
// most closely matches the prompt; medium and hard get progressively more
// adventurous.
// Governing: SPEC music-provider-integration REQ-PROV-053
const (
	RadioModeEasy   = "easy"
	RadioModeMedium = "medium"
	RadioModeHard   = "hard"
)

// ValidRadioMode reports whether mode is one of the lb-radio modes. The empty
// string is not valid here; RadioPlaylist defaults it to easy before checking.
func ValidRadioMode(mode string) bool {
	return mode == RadioModeEasy || mode == RadioModeMedium || mode == RadioModeHard
}

// radioResponse mirrors GET /1/explore/lb-radio: the generated playlist rides
// in payload.jspf (a JSPF document, i.e. {"playlist": {...}}), and
// payload.feedback carries human-readable notes about the generation.
type radioResponse struct {
	Payload struct {
		JSPF struct {
			Playlist jspfPlaylist `json:"playlist"`
		} `json:"jspf"`
		Feedback []string `json:"feedback"`
	} `json:"payload"`
}

// RadioPlaylist generates a track list from an LB Radio prompt (e.g.
// "artist:(radiohead)", "tag:(jazz)") via GET /1/explore/lb-radio and
// normalizes it like any other ListenBrainz JSPF playlist: recording MBIDs
// are parsed from the track identifiers and ride providers.Track.ID (the
// remote_id slot), so the persisted rows flow through the existing catalog
// linking and Navidrome matching unchanged (ADR-0014 — no MBID tier, so
// matching is by name/artist).
//
// The returned Playlist carries the deterministic identity used for
// regenerate-in-place upserts: ID is "lb-radio:<prompt>" (mode is a
// generation knob, not part of the key) and Name is "LB Radio: <prompt>".
// A generation that yields zero tracks is not an error at this layer; the
// caller decides how to surface it (the feedback strings are logged).
//
// NOTE on auth: per the ListenBrainz API docs the explore endpoints are
// anonymous, but authenticated requests get the higher per-token rate limit,
// so the user's token is sent whenever the provider has one. All requests go
// through doRequest and inherit the shared User-Agent and strict 429
// Retry-After semantics (REQ-PROV-047).
// Governing: ADR-0030, SPEC music-provider-integration REQ-PROV-053
func (p *Provider) RadioPlaylist(ctx context.Context, prompt, mode string) (providers.Playlist, error) {
	prompt = strings.TrimSpace(prompt)
	if prompt == "" {
		return providers.Playlist{}, fmt.Errorf("lb-radio prompt is required")
	}
	if mode == "" {
		mode = RadioModeEasy
	}
	if !ValidRadioMode(mode) {
		return providers.Playlist{}, fmt.Errorf("invalid lb-radio mode %q (must be easy, medium, or hard)", mode)
	}

	p.logger.Info("generating lb-radio playlist", "prompt", prompt, "mode", mode)

	query := url.Values{}
	query.Set("prompt", prompt)
	query.Set("mode", mode)

	token := ""
	if p.auth != nil {
		token = p.auth.Token
	}

	var result radioResponse
	if err := p.doRequest(ctx, http.MethodGet, "/1/explore/lb-radio?"+query.Encode(), token, &result); err != nil {
		return providers.Playlist{}, fmt.Errorf("failed to generate lb-radio playlist: %w", err)
	}

	for _, fb := range result.Payload.Feedback {
		p.logger.Debug("lb-radio feedback", "prompt", prompt, "feedback", fb)
	}

	// Reuse the JSPF normalization from playlist import (#56), then stamp the
	// deterministic local identity over the server-assigned title/identifier.
	pl := p.normalizePlaylist("", result.Payload.JSPF.Playlist)
	pl.ID = RadioRemoteID(prompt)
	pl.Name = "LB Radio: " + prompt
	pl.Description = radioDescription(prompt, mode)
	pl.ExternalURL = "" // generated on the fly; there is no page to deep-link

	p.logger.Info("generated lb-radio playlist", "prompt", prompt, "mode", mode, "tracks", len(pl.Tracks))
	return pl, nil
}

// RadioRemoteID derives the deterministic playlist remote ID for an LB Radio
// prompt. Same trimmed prompt => same remote ID => regeneration updates the
// existing playlist row instead of duplicating it.
// Governing: ADR-0030 (regenerate-in-place semantics), SPEC music-provider-integration REQ-PROV-053
func RadioRemoteID(prompt string) string {
	return providers.ListenBrainzRadioRemoteIDPrefix + strings.TrimSpace(prompt)
}

// radioDescription records how the playlist was generated (the mode is not
// part of the upsert key, so it is surfaced here).
func radioDescription(prompt, mode string) string {
	return fmt.Sprintf("Generated by ListenBrainz LB Radio (mode: %s) from prompt: %s", mode, prompt)
}
