// Code generated by ent, DO NOT EDIT.

package listen

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the listen type in the database.
	Label = "listen"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTrackName holds the string denoting the track_name field in the database.
	FieldTrackName = "track_name"
	// FieldArtistName holds the string denoting the artist_name field in the database.
	FieldArtistName = "artist_name"
	// FieldAlbumName holds the string denoting the album_name field in the database.
	FieldAlbumName = "album_name"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldPlayedAt holds the string denoting the played_at field in the database.
	FieldPlayedAt = "played_at"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the listen in the database.
	Table = "listens"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "listens"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_listens"
)

// Columns holds all SQL columns for listen fields.
var Columns = []string{
	FieldID,
	FieldTrackName,
	FieldArtistName,
	FieldAlbumName,
	FieldSource,
	FieldPlayedAt,
	FieldURL,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "listens"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_listens",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Listen queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTrackName orders the results by the track_name field.
func ByTrackName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrackName, opts...).ToFunc()
}

// ByArtistName orders the results by the artist_name field.
func ByArtistName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArtistName, opts...).ToFunc()
}

// ByAlbumName orders the results by the album_name field.
func ByAlbumName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlbumName, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByPlayedAt orders the results by the played_at field.
func ByPlayedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlayedAt, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
