// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldLastLoginAt holds the string denoting the last_login_at field in the database.
	FieldLastLoginAt = "last_login_at"
	// EdgeSpotifyAuth holds the string denoting the spotify_auth edge name in mutations.
	EdgeSpotifyAuth = "spotify_auth"
	// EdgeLastfmAuth holds the string denoting the lastfm_auth edge name in mutations.
	EdgeLastfmAuth = "lastfm_auth"
	// EdgeListens holds the string denoting the listens edge name in mutations.
	EdgeListens = "listens"
	// Table holds the table name of the user in the database.
	Table = "users"
	// SpotifyAuthTable is the table that holds the spotify_auth relation/edge.
	SpotifyAuthTable = "spotify_auths"
	// SpotifyAuthInverseTable is the table name for the SpotifyAuth entity.
	// It exists in this package in order to avoid circular dependency with the "spotifyauth" package.
	SpotifyAuthInverseTable = "spotify_auths"
	// SpotifyAuthColumn is the table column denoting the spotify_auth relation/edge.
	SpotifyAuthColumn = "user_spotify_auth"
	// LastfmAuthTable is the table that holds the lastfm_auth relation/edge.
	LastfmAuthTable = "last_fm_auths"
	// LastfmAuthInverseTable is the table name for the LastFMAuth entity.
	// It exists in this package in order to avoid circular dependency with the "lastfmauth" package.
	LastfmAuthInverseTable = "last_fm_auths"
	// LastfmAuthColumn is the table column denoting the lastfm_auth relation/edge.
	LastfmAuthColumn = "user_lastfm_auth"
	// ListensTable is the table that holds the listens relation/edge.
	ListensTable = "listens"
	// ListensInverseTable is the table name for the Listen entity.
	// It exists in this package in order to avoid circular dependency with the "listen" package.
	ListensInverseTable = "listens"
	// ListensColumn is the table column denoting the listens relation/edge.
	ListensColumn = "user_listens"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldEmail,
	FieldLastLoginAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLastLoginAt holds the default value on creation for the "last_login_at" field.
	DefaultLastLoginAt func() time.Time
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByLastLoginAt orders the results by the last_login_at field.
func ByLastLoginAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastLoginAt, opts...).ToFunc()
}

// BySpotifyAuthField orders the results by spotify_auth field.
func BySpotifyAuthField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSpotifyAuthStep(), sql.OrderByField(field, opts...))
	}
}

// ByLastfmAuthField orders the results by lastfm_auth field.
func ByLastfmAuthField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLastfmAuthStep(), sql.OrderByField(field, opts...))
	}
}

// ByListensCount orders the results by listens count.
func ByListensCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newListensStep(), opts...)
	}
}

// ByListens orders the results by listens terms.
func ByListens(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newListensStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSpotifyAuthStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SpotifyAuthInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, SpotifyAuthTable, SpotifyAuthColumn),
	)
}
func newLastfmAuthStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LastfmAuthInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, LastfmAuthTable, LastfmAuthColumn),
	)
}
func newListensStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ListensInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ListensTable, ListensColumn),
	)
}
