// Code generated by ent, DO NOT EDIT.

package user

import (
	"spotter/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUsername, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// Theme applies equality check predicate on the "theme" field. It's identical to ThemeEQ.
func Theme(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTheme, v))
}

// SystemPrompt applies equality check predicate on the "system_prompt" field. It's identical to SystemPromptEQ.
func SystemPrompt(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSystemPrompt, v))
}

// PaginationSize applies equality check predicate on the "pagination_size" field. It's identical to PaginationSizeEQ.
func PaginationSize(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPaginationSize, v))
}

// LastLoginAt applies equality check predicate on the "last_login_at" field. It's identical to LastLoginAtEQ.
func LastLoginAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLastLoginAt, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldUsername, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailIsNil applies the IsNil predicate on the "email" field.
func EmailIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldEmail))
}

// EmailNotNil applies the NotNil predicate on the "email" field.
func EmailNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldEmail))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldEmail, v))
}

// ThemeEQ applies the EQ predicate on the "theme" field.
func ThemeEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTheme, v))
}

// ThemeNEQ applies the NEQ predicate on the "theme" field.
func ThemeNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldTheme, v))
}

// ThemeIn applies the In predicate on the "theme" field.
func ThemeIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldTheme, vs...))
}

// ThemeNotIn applies the NotIn predicate on the "theme" field.
func ThemeNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldTheme, vs...))
}

// ThemeGT applies the GT predicate on the "theme" field.
func ThemeGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldTheme, v))
}

// ThemeGTE applies the GTE predicate on the "theme" field.
func ThemeGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldTheme, v))
}

// ThemeLT applies the LT predicate on the "theme" field.
func ThemeLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldTheme, v))
}

// ThemeLTE applies the LTE predicate on the "theme" field.
func ThemeLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldTheme, v))
}

// ThemeContains applies the Contains predicate on the "theme" field.
func ThemeContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldTheme, v))
}

// ThemeHasPrefix applies the HasPrefix predicate on the "theme" field.
func ThemeHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldTheme, v))
}

// ThemeHasSuffix applies the HasSuffix predicate on the "theme" field.
func ThemeHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldTheme, v))
}

// ThemeEqualFold applies the EqualFold predicate on the "theme" field.
func ThemeEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldTheme, v))
}

// ThemeContainsFold applies the ContainsFold predicate on the "theme" field.
func ThemeContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldTheme, v))
}

// SystemPromptEQ applies the EQ predicate on the "system_prompt" field.
func SystemPromptEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSystemPrompt, v))
}

// SystemPromptNEQ applies the NEQ predicate on the "system_prompt" field.
func SystemPromptNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldSystemPrompt, v))
}

// SystemPromptIn applies the In predicate on the "system_prompt" field.
func SystemPromptIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldSystemPrompt, vs...))
}

// SystemPromptNotIn applies the NotIn predicate on the "system_prompt" field.
func SystemPromptNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldSystemPrompt, vs...))
}

// SystemPromptGT applies the GT predicate on the "system_prompt" field.
func SystemPromptGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldSystemPrompt, v))
}

// SystemPromptGTE applies the GTE predicate on the "system_prompt" field.
func SystemPromptGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldSystemPrompt, v))
}

// SystemPromptLT applies the LT predicate on the "system_prompt" field.
func SystemPromptLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldSystemPrompt, v))
}

// SystemPromptLTE applies the LTE predicate on the "system_prompt" field.
func SystemPromptLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldSystemPrompt, v))
}

// SystemPromptContains applies the Contains predicate on the "system_prompt" field.
func SystemPromptContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldSystemPrompt, v))
}

// SystemPromptHasPrefix applies the HasPrefix predicate on the "system_prompt" field.
func SystemPromptHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldSystemPrompt, v))
}

// SystemPromptHasSuffix applies the HasSuffix predicate on the "system_prompt" field.
func SystemPromptHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldSystemPrompt, v))
}

// SystemPromptIsNil applies the IsNil predicate on the "system_prompt" field.
func SystemPromptIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldSystemPrompt))
}

// SystemPromptNotNil applies the NotNil predicate on the "system_prompt" field.
func SystemPromptNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldSystemPrompt))
}

// SystemPromptEqualFold applies the EqualFold predicate on the "system_prompt" field.
func SystemPromptEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldSystemPrompt, v))
}

// SystemPromptContainsFold applies the ContainsFold predicate on the "system_prompt" field.
func SystemPromptContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldSystemPrompt, v))
}

// PaginationSizeEQ applies the EQ predicate on the "pagination_size" field.
func PaginationSizeEQ(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPaginationSize, v))
}

// PaginationSizeNEQ applies the NEQ predicate on the "pagination_size" field.
func PaginationSizeNEQ(v int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldPaginationSize, v))
}

// PaginationSizeIn applies the In predicate on the "pagination_size" field.
func PaginationSizeIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldPaginationSize, vs...))
}

// PaginationSizeNotIn applies the NotIn predicate on the "pagination_size" field.
func PaginationSizeNotIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldPaginationSize, vs...))
}

// PaginationSizeGT applies the GT predicate on the "pagination_size" field.
func PaginationSizeGT(v int) predicate.User {
	return predicate.User(sql.FieldGT(FieldPaginationSize, v))
}

// PaginationSizeGTE applies the GTE predicate on the "pagination_size" field.
func PaginationSizeGTE(v int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldPaginationSize, v))
}

// PaginationSizeLT applies the LT predicate on the "pagination_size" field.
func PaginationSizeLT(v int) predicate.User {
	return predicate.User(sql.FieldLT(FieldPaginationSize, v))
}

// PaginationSizeLTE applies the LTE predicate on the "pagination_size" field.
func PaginationSizeLTE(v int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldPaginationSize, v))
}

// LastLoginAtEQ applies the EQ predicate on the "last_login_at" field.
func LastLoginAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLastLoginAt, v))
}

// LastLoginAtNEQ applies the NEQ predicate on the "last_login_at" field.
func LastLoginAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldLastLoginAt, v))
}

// LastLoginAtIn applies the In predicate on the "last_login_at" field.
func LastLoginAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldLastLoginAt, vs...))
}

// LastLoginAtNotIn applies the NotIn predicate on the "last_login_at" field.
func LastLoginAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldLastLoginAt, vs...))
}

// LastLoginAtGT applies the GT predicate on the "last_login_at" field.
func LastLoginAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldLastLoginAt, v))
}

// LastLoginAtGTE applies the GTE predicate on the "last_login_at" field.
func LastLoginAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldLastLoginAt, v))
}

// LastLoginAtLT applies the LT predicate on the "last_login_at" field.
func LastLoginAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldLastLoginAt, v))
}

// LastLoginAtLTE applies the LTE predicate on the "last_login_at" field.
func LastLoginAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldLastLoginAt, v))
}

// HasSpotifyAuth applies the HasEdge predicate on the "spotify_auth" edge.
func HasSpotifyAuth() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, SpotifyAuthTable, SpotifyAuthColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSpotifyAuthWith applies the HasEdge predicate on the "spotify_auth" edge with a given conditions (other predicates).
func HasSpotifyAuthWith(preds ...predicate.SpotifyAuth) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newSpotifyAuthStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLastfmAuth applies the HasEdge predicate on the "lastfm_auth" edge.
func HasLastfmAuth() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, LastfmAuthTable, LastfmAuthColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLastfmAuthWith applies the HasEdge predicate on the "lastfm_auth" edge with a given conditions (other predicates).
func HasLastfmAuthWith(preds ...predicate.LastFMAuth) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newLastfmAuthStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasNavidromeAuth applies the HasEdge predicate on the "navidrome_auth" edge.
func HasNavidromeAuth() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, NavidromeAuthTable, NavidromeAuthColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNavidromeAuthWith applies the HasEdge predicate on the "navidrome_auth" edge with a given conditions (other predicates).
func HasNavidromeAuthWith(preds ...predicate.NavidromeAuth) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newNavidromeAuthStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPlaylists applies the HasEdge predicate on the "playlists" edge.
func HasPlaylists() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PlaylistsTable, PlaylistsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlaylistsWith applies the HasEdge predicate on the "playlists" edge with a given conditions (other predicates).
func HasPlaylistsWith(preds ...predicate.Playlist) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newPlaylistsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasListens applies the HasEdge predicate on the "listens" edge.
func HasListens() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ListensTable, ListensColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasListensWith applies the HasEdge predicate on the "listens" edge with a given conditions (other predicates).
func HasListensWith(preds ...predicate.Listen) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newListensStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSyncEvents applies the HasEdge predicate on the "sync_events" edge.
func HasSyncEvents() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SyncEventsTable, SyncEventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSyncEventsWith applies the HasEdge predicate on the "sync_events" edge with a given conditions (other predicates).
func HasSyncEventsWith(preds ...predicate.SyncEvent) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newSyncEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasArtists applies the HasEdge predicate on the "artists" edge.
func HasArtists() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ArtistsTable, ArtistsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasArtistsWith applies the HasEdge predicate on the "artists" edge with a given conditions (other predicates).
func HasArtistsWith(preds ...predicate.Artist) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newArtistsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAlbums applies the HasEdge predicate on the "albums" edge.
func HasAlbums() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AlbumsTable, AlbumsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAlbumsWith applies the HasEdge predicate on the "albums" edge with a given conditions (other predicates).
func HasAlbumsWith(preds ...predicate.Album) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newAlbumsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDjs applies the HasEdge predicate on the "djs" edge.
func HasDjs() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DjsTable, DjsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDjsWith applies the HasEdge predicate on the "djs" edge with a given conditions (other predicates).
func HasDjsWith(preds ...predicate.DJ) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newDjsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMixtapes applies the HasEdge predicate on the "mixtapes" edge.
func HasMixtapes() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MixtapesTable, MixtapesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMixtapesWith applies the HasEdge predicate on the "mixtapes" edge with a given conditions (other predicates).
func HasMixtapesWith(preds ...predicate.Mixtape) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newMixtapesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
