// Code generated by ent, DO NOT EDIT.

package playlist

import (
	"spotter/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Playlist {
	return predicate.Playlist(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Playlist {
	return predicate.Playlist(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Playlist {
	return predicate.Playlist(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Playlist {
	return predicate.Playlist(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Playlist {
	return predicate.Playlist(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Playlist {
	return predicate.Playlist(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Playlist {
	return predicate.Playlist(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Playlist {
	return predicate.Playlist(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Playlist {
	return predicate.Playlist(sql.FieldLTE(FieldID, id))
}

// RemoteID applies equality check predicate on the "remote_id" field. It's identical to RemoteIDEQ.
func RemoteID(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldEQ(FieldRemoteID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldEQ(FieldDescription, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldEQ(FieldSource, v))
}

// ImageURL applies equality check predicate on the "image_url" field. It's identical to ImageURLEQ.
func ImageURL(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldEQ(FieldImageURL, v))
}

// ExternalURL applies equality check predicate on the "external_url" field. It's identical to ExternalURLEQ.
func ExternalURL(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldEQ(FieldExternalURL, v))
}

// TrackCount applies equality check predicate on the "track_count" field. It's identical to TrackCountEQ.
func TrackCount(v int) predicate.Playlist {
	return predicate.Playlist(sql.FieldEQ(FieldTrackCount, v))
}

// UniqueArtists applies equality check predicate on the "unique_artists" field. It's identical to UniqueArtistsEQ.
func UniqueArtists(v int) predicate.Playlist {
	return predicate.Playlist(sql.FieldEQ(FieldUniqueArtists, v))
}

// UniqueAlbums applies equality check predicate on the "unique_albums" field. It's identical to UniqueAlbumsEQ.
func UniqueAlbums(v int) predicate.Playlist {
	return predicate.Playlist(sql.FieldEQ(FieldUniqueAlbums, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Playlist {
	return predicate.Playlist(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Playlist {
	return predicate.Playlist(sql.FieldEQ(FieldUpdatedAt, v))
}

// RemoteIDEQ applies the EQ predicate on the "remote_id" field.
func RemoteIDEQ(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldEQ(FieldRemoteID, v))
}

// RemoteIDNEQ applies the NEQ predicate on the "remote_id" field.
func RemoteIDNEQ(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldNEQ(FieldRemoteID, v))
}

// RemoteIDIn applies the In predicate on the "remote_id" field.
func RemoteIDIn(vs ...string) predicate.Playlist {
	return predicate.Playlist(sql.FieldIn(FieldRemoteID, vs...))
}

// RemoteIDNotIn applies the NotIn predicate on the "remote_id" field.
func RemoteIDNotIn(vs ...string) predicate.Playlist {
	return predicate.Playlist(sql.FieldNotIn(FieldRemoteID, vs...))
}

// RemoteIDGT applies the GT predicate on the "remote_id" field.
func RemoteIDGT(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldGT(FieldRemoteID, v))
}

// RemoteIDGTE applies the GTE predicate on the "remote_id" field.
func RemoteIDGTE(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldGTE(FieldRemoteID, v))
}

// RemoteIDLT applies the LT predicate on the "remote_id" field.
func RemoteIDLT(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldLT(FieldRemoteID, v))
}

// RemoteIDLTE applies the LTE predicate on the "remote_id" field.
func RemoteIDLTE(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldLTE(FieldRemoteID, v))
}

// RemoteIDContains applies the Contains predicate on the "remote_id" field.
func RemoteIDContains(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldContains(FieldRemoteID, v))
}

// RemoteIDHasPrefix applies the HasPrefix predicate on the "remote_id" field.
func RemoteIDHasPrefix(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldHasPrefix(FieldRemoteID, v))
}

// RemoteIDHasSuffix applies the HasSuffix predicate on the "remote_id" field.
func RemoteIDHasSuffix(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldHasSuffix(FieldRemoteID, v))
}

// RemoteIDEqualFold applies the EqualFold predicate on the "remote_id" field.
func RemoteIDEqualFold(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldEqualFold(FieldRemoteID, v))
}

// RemoteIDContainsFold applies the ContainsFold predicate on the "remote_id" field.
func RemoteIDContainsFold(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldContainsFold(FieldRemoteID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Playlist {
	return predicate.Playlist(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Playlist {
	return predicate.Playlist(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Playlist {
	return predicate.Playlist(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Playlist {
	return predicate.Playlist(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Playlist {
	return predicate.Playlist(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Playlist {
	return predicate.Playlist(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldContainsFold(FieldDescription, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.Playlist {
	return predicate.Playlist(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.Playlist {
	return predicate.Playlist(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldContainsFold(FieldSource, v))
}

// ImageURLEQ applies the EQ predicate on the "image_url" field.
func ImageURLEQ(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldEQ(FieldImageURL, v))
}

// ImageURLNEQ applies the NEQ predicate on the "image_url" field.
func ImageURLNEQ(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldNEQ(FieldImageURL, v))
}

// ImageURLIn applies the In predicate on the "image_url" field.
func ImageURLIn(vs ...string) predicate.Playlist {
	return predicate.Playlist(sql.FieldIn(FieldImageURL, vs...))
}

// ImageURLNotIn applies the NotIn predicate on the "image_url" field.
func ImageURLNotIn(vs ...string) predicate.Playlist {
	return predicate.Playlist(sql.FieldNotIn(FieldImageURL, vs...))
}

// ImageURLGT applies the GT predicate on the "image_url" field.
func ImageURLGT(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldGT(FieldImageURL, v))
}

// ImageURLGTE applies the GTE predicate on the "image_url" field.
func ImageURLGTE(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldGTE(FieldImageURL, v))
}

// ImageURLLT applies the LT predicate on the "image_url" field.
func ImageURLLT(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldLT(FieldImageURL, v))
}

// ImageURLLTE applies the LTE predicate on the "image_url" field.
func ImageURLLTE(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldLTE(FieldImageURL, v))
}

// ImageURLContains applies the Contains predicate on the "image_url" field.
func ImageURLContains(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldContains(FieldImageURL, v))
}

// ImageURLHasPrefix applies the HasPrefix predicate on the "image_url" field.
func ImageURLHasPrefix(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldHasPrefix(FieldImageURL, v))
}

// ImageURLHasSuffix applies the HasSuffix predicate on the "image_url" field.
func ImageURLHasSuffix(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldHasSuffix(FieldImageURL, v))
}

// ImageURLIsNil applies the IsNil predicate on the "image_url" field.
func ImageURLIsNil() predicate.Playlist {
	return predicate.Playlist(sql.FieldIsNull(FieldImageURL))
}

// ImageURLNotNil applies the NotNil predicate on the "image_url" field.
func ImageURLNotNil() predicate.Playlist {
	return predicate.Playlist(sql.FieldNotNull(FieldImageURL))
}

// ImageURLEqualFold applies the EqualFold predicate on the "image_url" field.
func ImageURLEqualFold(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldEqualFold(FieldImageURL, v))
}

// ImageURLContainsFold applies the ContainsFold predicate on the "image_url" field.
func ImageURLContainsFold(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldContainsFold(FieldImageURL, v))
}

// ExternalURLEQ applies the EQ predicate on the "external_url" field.
func ExternalURLEQ(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldEQ(FieldExternalURL, v))
}

// ExternalURLNEQ applies the NEQ predicate on the "external_url" field.
func ExternalURLNEQ(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldNEQ(FieldExternalURL, v))
}

// ExternalURLIn applies the In predicate on the "external_url" field.
func ExternalURLIn(vs ...string) predicate.Playlist {
	return predicate.Playlist(sql.FieldIn(FieldExternalURL, vs...))
}

// ExternalURLNotIn applies the NotIn predicate on the "external_url" field.
func ExternalURLNotIn(vs ...string) predicate.Playlist {
	return predicate.Playlist(sql.FieldNotIn(FieldExternalURL, vs...))
}

// ExternalURLGT applies the GT predicate on the "external_url" field.
func ExternalURLGT(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldGT(FieldExternalURL, v))
}

// ExternalURLGTE applies the GTE predicate on the "external_url" field.
func ExternalURLGTE(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldGTE(FieldExternalURL, v))
}

// ExternalURLLT applies the LT predicate on the "external_url" field.
func ExternalURLLT(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldLT(FieldExternalURL, v))
}

// ExternalURLLTE applies the LTE predicate on the "external_url" field.
func ExternalURLLTE(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldLTE(FieldExternalURL, v))
}

// ExternalURLContains applies the Contains predicate on the "external_url" field.
func ExternalURLContains(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldContains(FieldExternalURL, v))
}

// ExternalURLHasPrefix applies the HasPrefix predicate on the "external_url" field.
func ExternalURLHasPrefix(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldHasPrefix(FieldExternalURL, v))
}

// ExternalURLHasSuffix applies the HasSuffix predicate on the "external_url" field.
func ExternalURLHasSuffix(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldHasSuffix(FieldExternalURL, v))
}

// ExternalURLIsNil applies the IsNil predicate on the "external_url" field.
func ExternalURLIsNil() predicate.Playlist {
	return predicate.Playlist(sql.FieldIsNull(FieldExternalURL))
}

// ExternalURLNotNil applies the NotNil predicate on the "external_url" field.
func ExternalURLNotNil() predicate.Playlist {
	return predicate.Playlist(sql.FieldNotNull(FieldExternalURL))
}

// ExternalURLEqualFold applies the EqualFold predicate on the "external_url" field.
func ExternalURLEqualFold(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldEqualFold(FieldExternalURL, v))
}

// ExternalURLContainsFold applies the ContainsFold predicate on the "external_url" field.
func ExternalURLContainsFold(v string) predicate.Playlist {
	return predicate.Playlist(sql.FieldContainsFold(FieldExternalURL, v))
}

// TrackCountEQ applies the EQ predicate on the "track_count" field.
func TrackCountEQ(v int) predicate.Playlist {
	return predicate.Playlist(sql.FieldEQ(FieldTrackCount, v))
}

// TrackCountNEQ applies the NEQ predicate on the "track_count" field.
func TrackCountNEQ(v int) predicate.Playlist {
	return predicate.Playlist(sql.FieldNEQ(FieldTrackCount, v))
}

// TrackCountIn applies the In predicate on the "track_count" field.
func TrackCountIn(vs ...int) predicate.Playlist {
	return predicate.Playlist(sql.FieldIn(FieldTrackCount, vs...))
}

// TrackCountNotIn applies the NotIn predicate on the "track_count" field.
func TrackCountNotIn(vs ...int) predicate.Playlist {
	return predicate.Playlist(sql.FieldNotIn(FieldTrackCount, vs...))
}

// TrackCountGT applies the GT predicate on the "track_count" field.
func TrackCountGT(v int) predicate.Playlist {
	return predicate.Playlist(sql.FieldGT(FieldTrackCount, v))
}

// TrackCountGTE applies the GTE predicate on the "track_count" field.
func TrackCountGTE(v int) predicate.Playlist {
	return predicate.Playlist(sql.FieldGTE(FieldTrackCount, v))
}

// TrackCountLT applies the LT predicate on the "track_count" field.
func TrackCountLT(v int) predicate.Playlist {
	return predicate.Playlist(sql.FieldLT(FieldTrackCount, v))
}

// TrackCountLTE applies the LTE predicate on the "track_count" field.
func TrackCountLTE(v int) predicate.Playlist {
	return predicate.Playlist(sql.FieldLTE(FieldTrackCount, v))
}

// UniqueArtistsEQ applies the EQ predicate on the "unique_artists" field.
func UniqueArtistsEQ(v int) predicate.Playlist {
	return predicate.Playlist(sql.FieldEQ(FieldUniqueArtists, v))
}

// UniqueArtistsNEQ applies the NEQ predicate on the "unique_artists" field.
func UniqueArtistsNEQ(v int) predicate.Playlist {
	return predicate.Playlist(sql.FieldNEQ(FieldUniqueArtists, v))
}

// UniqueArtistsIn applies the In predicate on the "unique_artists" field.
func UniqueArtistsIn(vs ...int) predicate.Playlist {
	return predicate.Playlist(sql.FieldIn(FieldUniqueArtists, vs...))
}

// UniqueArtistsNotIn applies the NotIn predicate on the "unique_artists" field.
func UniqueArtistsNotIn(vs ...int) predicate.Playlist {
	return predicate.Playlist(sql.FieldNotIn(FieldUniqueArtists, vs...))
}

// UniqueArtistsGT applies the GT predicate on the "unique_artists" field.
func UniqueArtistsGT(v int) predicate.Playlist {
	return predicate.Playlist(sql.FieldGT(FieldUniqueArtists, v))
}

// UniqueArtistsGTE applies the GTE predicate on the "unique_artists" field.
func UniqueArtistsGTE(v int) predicate.Playlist {
	return predicate.Playlist(sql.FieldGTE(FieldUniqueArtists, v))
}

// UniqueArtistsLT applies the LT predicate on the "unique_artists" field.
func UniqueArtistsLT(v int) predicate.Playlist {
	return predicate.Playlist(sql.FieldLT(FieldUniqueArtists, v))
}

// UniqueArtistsLTE applies the LTE predicate on the "unique_artists" field.
func UniqueArtistsLTE(v int) predicate.Playlist {
	return predicate.Playlist(sql.FieldLTE(FieldUniqueArtists, v))
}

// UniqueAlbumsEQ applies the EQ predicate on the "unique_albums" field.
func UniqueAlbumsEQ(v int) predicate.Playlist {
	return predicate.Playlist(sql.FieldEQ(FieldUniqueAlbums, v))
}

// UniqueAlbumsNEQ applies the NEQ predicate on the "unique_albums" field.
func UniqueAlbumsNEQ(v int) predicate.Playlist {
	return predicate.Playlist(sql.FieldNEQ(FieldUniqueAlbums, v))
}

// UniqueAlbumsIn applies the In predicate on the "unique_albums" field.
func UniqueAlbumsIn(vs ...int) predicate.Playlist {
	return predicate.Playlist(sql.FieldIn(FieldUniqueAlbums, vs...))
}

// UniqueAlbumsNotIn applies the NotIn predicate on the "unique_albums" field.
func UniqueAlbumsNotIn(vs ...int) predicate.Playlist {
	return predicate.Playlist(sql.FieldNotIn(FieldUniqueAlbums, vs...))
}

// UniqueAlbumsGT applies the GT predicate on the "unique_albums" field.
func UniqueAlbumsGT(v int) predicate.Playlist {
	return predicate.Playlist(sql.FieldGT(FieldUniqueAlbums, v))
}

// UniqueAlbumsGTE applies the GTE predicate on the "unique_albums" field.
func UniqueAlbumsGTE(v int) predicate.Playlist {
	return predicate.Playlist(sql.FieldGTE(FieldUniqueAlbums, v))
}

// UniqueAlbumsLT applies the LT predicate on the "unique_albums" field.
func UniqueAlbumsLT(v int) predicate.Playlist {
	return predicate.Playlist(sql.FieldLT(FieldUniqueAlbums, v))
}

// UniqueAlbumsLTE applies the LTE predicate on the "unique_albums" field.
func UniqueAlbumsLTE(v int) predicate.Playlist {
	return predicate.Playlist(sql.FieldLTE(FieldUniqueAlbums, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Playlist {
	return predicate.Playlist(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Playlist {
	return predicate.Playlist(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Playlist {
	return predicate.Playlist(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Playlist {
	return predicate.Playlist(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Playlist {
	return predicate.Playlist(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Playlist {
	return predicate.Playlist(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Playlist {
	return predicate.Playlist(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Playlist {
	return predicate.Playlist(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Playlist {
	return predicate.Playlist(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Playlist {
	return predicate.Playlist(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Playlist {
	return predicate.Playlist(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Playlist {
	return predicate.Playlist(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Playlist {
	return predicate.Playlist(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Playlist {
	return predicate.Playlist(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Playlist {
	return predicate.Playlist(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Playlist {
	return predicate.Playlist(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Playlist {
	return predicate.Playlist(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Playlist {
	return predicate.Playlist(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Playlist) predicate.Playlist {
	return predicate.Playlist(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Playlist) predicate.Playlist {
	return predicate.Playlist(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Playlist) predicate.Playlist {
	return predicate.Playlist(sql.NotPredicates(p))
}
